// Copyright 2018 Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0
//
// Portions Copyright 2017 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the THIRD-PARTY file.

//! Virtual Machine Monitor that leverages the Linux Kernel-based Virtual Machine (KVM),
//! and other virtualization features to run a single lightweight micro-virtual
//! machine (microVM).
//#![deny(missing_docs)]

#[macro_use]
extern crate log;

/// Handles setup and initialization a `Vmm` object.
pub mod builder;
pub(crate) mod device_manager;
/// Dirty page bitmap for incremental snapshots.
pub mod dirty_bitmap;
/// Resource store for configured microVM resources.
pub mod resources;
/// Signal handling utilities.
#[cfg(target_os = "linux")]
pub mod signal_handler;
/// VM snapshot and restore support.
pub mod snapshot;
/// Snapshot store abstraction for flexible backends.
#[cfg(feature = "snapshot")]
pub mod snapshot_store;
/// UFFD handler for demand-paging during cold restore.
#[cfg(all(target_os = "linux", feature = "uffd"))]
pub mod uffd;
/// VM exit reasons and shared exit state.
pub mod vm_exit;
/// Wrappers over structures used to configure the VMM.
pub mod vmm_config;

#[cfg(target_os = "linux")]
mod linux;
#[cfg(target_os = "linux")]
use crate::linux::vstate;
#[cfg(target_os = "macos")]
mod macos;
mod terminal;
pub mod worker;

#[cfg(target_os = "macos")]
use macos::vstate;

use std::fmt::{Display, Formatter};
use std::io;
use std::os::unix::io::AsRawFd;
use std::sync::atomic::{AtomicBool, AtomicI32, Ordering};
use std::sync::{Arc, Mutex};
use std::time::Duration;

#[cfg(target_arch = "x86_64")]
use crate::device_manager::legacy::PortIODeviceManager;
use crate::device_manager::mmio::MMIODeviceManager;
use crate::vstate::VcpuEvent;
use crate::vstate::{Vcpu, VcpuHandle, VcpuResponse, Vm};

use arch::{ArchMemoryInfo, InitrdConfig};
#[cfg(target_os = "macos")]
use crossbeam_channel::Sender;
#[cfg(any(target_arch = "aarch64", target_arch = "riscv64"))]
use devices::fdt;
use devices::legacy::IrqChip;
use devices::virtio::VmmExitObserver;
use devices::{BusDevice, DeviceType};
use kernel::cmdline::Cmdline as KernelCmdline;
use polly::event_manager::{self, EventManager, Subscriber};
use utils::epoll::{EpollEvent, EventSet};
use utils::eventfd::EventFd;
#[cfg(target_os = "macos")]
use vm_memory::Address;
use vm_memory::GuestMemoryMmap;

/// Success exit code.
pub const FC_EXIT_CODE_OK: u8 = 0;
/// Generic error exit code.
pub const FC_EXIT_CODE_GENERIC_ERROR: u8 = 1;
/// Generic exit code for an error considered not possible to occur if the program logic is sound.
pub const FC_EXIT_CODE_UNEXPECTED_ERROR: u8 = 2;
/// Guest requested a reboot (KVM_SYSTEM_EVENT_RESET).
pub const FC_EXIT_CODE_REBOOT: u8 = 3;
/// Firecracker was shut down after intercepting a restricted system call.
pub const FC_EXIT_CODE_BAD_SYSCALL: u8 = 148;
/// Firecracker was shut down after intercepting `SIGBUS`.
pub const FC_EXIT_CODE_SIGBUS: u8 = 149;
/// Firecracker was shut down after intercepting `SIGSEGV`.
pub const FC_EXIT_CODE_SIGSEGV: u8 = 150;
/// Bad configuration for microvm's resources, when using a single json.
pub const FC_EXIT_CODE_BAD_CONFIGURATION: u8 = 152;
/// Command line arguments parsing error.
pub const FC_EXIT_CODE_ARG_PARSING: u8 = 153;

/// Errors associated with the VMM internal logic. These errors cannot be generated by direct user
/// input, but can result from bad configuration of the host (for example if Firecracker doesn't
/// have permissions to open the KVM fd).
#[derive(Debug)]
pub enum Error {
    /// This error is thrown by the minimal boot loader implementation.
    ConfigureSystem(arch::Error),
    /// Legacy devices work with Event file descriptors and the creation can fail because
    /// of resource exhaustion.
    #[cfg(target_arch = "x86_64")]
    CreateLegacyDevice(device_manager::legacy::Error),
    /// Cannot read from an Event file descriptor.
    EventFd(io::Error),
    /// Polly error wrapper.
    EventManager(event_manager::Error),
    /// I8042 Error.
    I8042Error(devices::legacy::I8042DeviceError),
    /// Cannot access kernel file.
    KernelFile(io::Error),
    /// Cannot open /dev/kvm. Either the host does not have KVM or Firecracker does not have
    /// permission to open the file descriptor.
    KvmContext(vstate::Error),
    #[cfg(target_arch = "x86_64")]
    /// Cannot add devices to the Legacy I/O Bus.
    LegacyIOBus(device_manager::legacy::Error),
    /// Cannot load command line.
    LoadCommandline(kernel::cmdline::Error),
    /// Cannot add a device to the MMIO Bus.
    RegisterMMIODevice(device_manager::mmio::Error),
    /// Write to the serial console failed.
    Serial(io::Error),
    /// Snapshot error.
    #[cfg(feature = "snapshot")]
    Snapshot(String),
    #[cfg(any(target_arch = "aarch64", target_arch = "riscv64"))]
    /// Cannot generate or write FDT
    SetupFDT(devices::fdt::Error),
    /// Cannot create Timer file descriptor.
    TimerFd(io::Error),
    /// Vcpu error.
    Vcpu(vstate::Error),
    /// Cannot send event to vCPU.
    VcpuEvent(vstate::Error),
    /// Cannot create a vCPU handle.
    VcpuHandle(vstate::Error),
    /// vCPU pause failed.
    VcpuPause,
    /// vCPU resume failed.
    VcpuResume,
    /// Cannot spawn a new Vcpu thread.
    VcpuSpawn(std::io::Error),
    /// Vm error.
    Vm(vstate::Error),
    /// Error thrown by observer object on Vmm initialization.
    VmmObserverInit(utils::errno::Error),
    /// Error thrown by observer object on Vmm teardown.
    VmmObserverTeardown(utils::errno::Error),
}

impl Display for Error {
    fn fmt(&self, f: &mut Formatter) -> std::fmt::Result {
        use self::Error::*;

        match self {
            ConfigureSystem(e) => write!(f, "System configuration error: {e:?}"),
            #[cfg(target_arch = "x86_64")]
            CreateLegacyDevice(e) => write!(f, "Error creating legacy device: {e:?}"),
            EventFd(e) => write!(f, "Event fd error: {e}"),
            EventManager(e) => write!(f, "Event manager error: {e:?}"),
            I8042Error(e) => write!(f, "I8042 error: {e}"),
            KernelFile(e) => write!(f, "Cannot access kernel file: {e}"),
            KvmContext(e) => write!(f, "Failed to validate KVM support: {e:?}"),
            #[cfg(target_arch = "x86_64")]
            LegacyIOBus(e) => write!(f, "Cannot add devices to the legacy I/O Bus. {e}"),
            LoadCommandline(e) => write!(f, "Cannot load command line: {e}"),
            RegisterMMIODevice(e) => write!(f, "Cannot add a device to the MMIO Bus. {e}"),
            Serial(e) => write!(f, "Error writing to the serial console: {e:?}"),
            #[cfg(feature = "snapshot")]
            Snapshot(e) => write!(f, "Snapshot error: {e}"),
            #[cfg(any(target_arch = "aarch64", target_arch = "riscv64"))]
            SetupFDT(e) => write!(f, "Error generating or writing FDT: {e:?}"),
            TimerFd(e) => write!(f, "Error creating timer fd: {e}"),
            Vcpu(e) => write!(f, "Vcpu error: {e}"),
            VcpuEvent(e) => write!(f, "Cannot send event to vCPU. {e:?}"),
            VcpuHandle(e) => write!(f, "Cannot create a vCPU handle. {e}"),
            VcpuPause => write!(f, "vCPUs pause failed."),
            VcpuResume => write!(f, "vCPUs resume failed."),
            VcpuSpawn(e) => write!(f, "Cannot spawn Vcpu thread: {e}"),
            Vm(e) => write!(f, "Vm error: {e}"),
            VmmObserverInit(e) => write!(
                f,
                "Error thrown by observer object on Vmm initialization: {e}"
            ),
            VmmObserverTeardown(e) => {
                write!(f, "Error thrown by observer object on Vmm teardown: {e}")
            }
        }
    }
}

/// Trait for objects that need custom initialization and teardown during the Vmm lifetime.
pub trait VmmEventsObserver {
    /// This function will be called during microVm boot.
    fn on_vmm_boot(&mut self) -> std::result::Result<(), utils::errno::Error> {
        Ok(())
    }
    /// This function will be called on microVm teardown.
    fn on_vmm_stop(&mut self) -> std::result::Result<(), utils::errno::Error> {
        Ok(())
    }
}

/// Shorthand result type for internal VMM commands.
pub type Result<T> = std::result::Result<T, Error>;

/// Contains the state and associated methods required for the Firecracker VMM.
pub struct Vmm {
    // Guest VM core resources.
    guest_memory: GuestMemoryMmap,
    arch_memory_info: ArchMemoryInfo,

    kernel_cmdline: KernelCmdline,

    vcpus_handles: Vec<VcpuHandle>,
    exit_evt: EventFd,
    vm: Vm,
    exit_observers: Vec<Arc<Mutex<dyn VmmExitObserver>>>,
    exit_code: Arc<AtomicI32>,
    vm_exit: crate::vm_exit::SharedVmExit,
    vcpu_exit_flag: Arc<AtomicBool>,

    // Guest VM devices.
    mmio_device_manager: MMIODeviceManager,
    #[cfg(target_arch = "x86_64")]
    pio_device_manager: PortIODeviceManager,
    #[cfg(target_os = "macos")]
    dirty_bitmaps: Arc<Vec<dirty_bitmap::DirtyBitmap>>,

    // Snapshot and dirty tracking state.
    #[cfg_attr(not(feature = "snapshot"), allow(dead_code))]
    nested_enabled: bool,
    #[cfg_attr(not(feature = "snapshot"), allow(dead_code))]
    dirty_tracking_enabled: bool,

    // Interrupt controller state needed for snapshots.
    #[cfg(target_os = "macos")]
    #[cfg_attr(not(feature = "snapshot"), allow(dead_code))]
    vcpu_list: Arc<devices::legacy::VcpuList>,
    #[cfg(target_os = "macos")]
    #[cfg_attr(not(feature = "snapshot"), allow(dead_code))]
    intc: IrqChip,
    #[cfg(all(target_os = "linux", target_arch = "aarch64", feature = "snapshot"))]
    intc: IrqChip,

    // Balloon device reference for snapshot-time exclusion of reclaimed pages.
    #[cfg(not(feature = "tee"))]
    pub(crate) balloon: Option<std::sync::Arc<std::sync::Mutex<devices::virtio::balloon::Balloon>>>,

    // VMGENID device for VM generation tracking (x86_64 and aarch64).
    #[cfg(any(target_arch = "x86_64", target_arch = "aarch64"))]
    pub(crate) vmgenid: Option<devices::vmgenid::Vmgenid>,
}

impl Vmm {
    /// Gets the balloon device reference if available.
    #[cfg(not(feature = "tee"))]
    pub fn get_balloon(
        &self,
    ) -> Option<&std::sync::Arc<std::sync::Mutex<devices::virtio::balloon::Balloon>>> {
        self.balloon.as_ref()
    }

    /// Gets the the specified bus device.
    pub fn get_bus_device(
        &self,
        device_type: DeviceType,
        device_id: &str,
    ) -> Option<&Mutex<dyn BusDevice>> {
        self.mmio_device_manager.get_device(device_type, device_id)
    }

    /// Starts the microVM vcpus.
    pub fn start_vcpus(&mut self, mut vcpus: Vec<Vcpu>) -> Result<()> {
        self.start_vcpus_paused(&mut vcpus)?;

        // The vcpus start off in the `Paused` state, let them run.
        self.resume_vcpus()?;

        Ok(())
    }

    /// Starts the microVM vcpus without resuming them.
    ///
    /// After this call vCPU threads exist but are sitting in their initial
    /// event loop waiting for Resume or RestoreState. Use this for cold
    /// restore from snapshot.
    pub fn start_vcpus_paused(&mut self, vcpus: &mut Vec<Vcpu>) -> Result<()> {
        Vcpu::register_kick_signal_handler();

        self.vcpus_handles.reserve(vcpus.len());

        for vcpu in vcpus.drain(..) {
            let mut vcpu = vcpu;
            vcpu.set_mmio_bus(self.mmio_device_manager.bus.clone());

            self.vcpus_handles
                .push(vcpu.start_threaded().map_err(Error::VcpuHandle)?);
        }

        Ok(())
    }

    /// Sends a pause command to all vcpus and waits for confirmation.
    pub fn pause_vcpus(&mut self) -> Result<()> {
        for handle in self.vcpus_handles.iter() {
            handle
                .send_event(VcpuEvent::Pause)
                .map_err(Error::VcpuEvent)?;
        }
        for handle in self.vcpus_handles.iter() {
            match handle
                .response_receiver()
                .recv_timeout(Duration::from_millis(1000))
            {
                Ok(VcpuResponse::Paused) => (),
                _ => return Err(Error::VcpuPause),
            }
        }
        Ok(())
    }

    /// Save all vCPU states. vCPUs must already be paused.
    #[cfg(target_os = "macos")]
    pub fn save_vcpu_states(&self) -> Result<Vec<hvf::Aarch64VcpuState>> {
        let mut states = Vec::with_capacity(self.vcpus_handles.len());
        for handle in self.vcpus_handles.iter() {
            states.push(handle.save_state().map_err(Error::Vcpu)?);
        }
        Ok(states)
    }

    /// Restore all vCPU states. vCPUs must already be paused.
    #[cfg(target_os = "macos")]
    pub fn restore_vcpu_states(&self, states: Vec<hvf::Aarch64VcpuState>) -> Result<()> {
        if states.len() != self.vcpus_handles.len() {
            return Err(Error::VcpuPause);
        }
        // Read host counter once so all vCPUs get the same reference point
        // (avoids inter-vCPU skew from restore loop timing).
        let host_now = hvf::host_counter_now();
        for (handle, mut state) in self.vcpus_handles.iter().zip(states.into_iter()) {
            state.host_counter_at_restore = Some(host_now);
            handle.restore_state(state).map_err(Error::Vcpu)?;
        }
        Ok(())
    }

    /// Save interrupt controller state (pending IRQs + GIC registers) for snapshot.
    #[cfg(all(target_os = "macos", feature = "snapshot"))]
    fn save_interrupt_controller_state(
        &self,
    ) -> std::result::Result<Option<Vec<u8>>, snapshot::SnapshotError> {
        let pending_irqs = self.vcpu_list.save_interrupt_state();
        let gic_registers = self.intc.lock().unwrap().save_snapshot_state();

        let ic_snapshot = snapshot::InterruptControllerSnapshot {
            pending_irqs,
            gic_registers,
        };

        let data = bincode_next::encode_to_vec(&ic_snapshot, bincode_next::config::standard())
            .map_err(|e| snapshot::SnapshotError::Serialize(e.to_string()))?;
        Ok(Some(data))
    }

    /// Restore interrupt controller state (pending IRQs + GIC registers) from snapshot.
    #[cfg(all(target_os = "macos", feature = "snapshot"))]
    fn restore_interrupt_controller_state(
        &self,
        data: &[u8],
    ) -> std::result::Result<(), snapshot::SnapshotError> {
        let ic_snapshot: snapshot::InterruptControllerSnapshot = bincode_next::decode_from_slice(data, bincode_next::config::standard().with_limit::<{ snapshot::VMSTATE_MAX_SIZE as usize }>())
            .map(|(val, _)| val)
            .map_err(|e| snapshot::SnapshotError::Deserialize(e.to_string()))?;

        self.vcpu_list
            .restore_interrupt_state(&ic_snapshot.pending_irqs);

        if let Some(gic_data) = &ic_snapshot.gic_registers {
            self.intc.lock().unwrap().restore_snapshot_state(gic_data);
        }

        Ok(())
    }

    /// Save all vCPU states as opaque bytes. vCPUs must already be paused.
    #[cfg(all(target_os = "linux", feature = "snapshot"))]
    pub fn save_vcpu_states(&self) -> Result<Vec<Vec<u8>>> {
        let mut states = Vec::with_capacity(self.vcpus_handles.len());
        for handle in self.vcpus_handles.iter() {
            states.push(handle.save_state().map_err(Error::Vcpu)?);
        }
        Ok(states)
    }

    /// Restore all vCPU states from opaque bytes. vCPUs must already be paused.
    #[cfg(all(target_os = "linux", feature = "snapshot"))]
    pub fn restore_vcpu_states(&self, states: Vec<Vec<u8>>) -> Result<()> {
        if states.len() != self.vcpus_handles.len() {
            return Err(Error::VcpuPause);
        }
        for (handle, state) in self.vcpus_handles.iter().zip(states.into_iter()) {
            handle.restore_state(state).map_err(Error::Vcpu)?;
        }
        Ok(())
    }

    /// Save interrupt controller state for snapshot (Linux/aarch64).
    #[cfg(all(target_os = "linux", target_arch = "aarch64", feature = "snapshot"))]
    fn save_interrupt_controller_state(
        &self,
    ) -> std::result::Result<Option<Vec<u8>>, snapshot::SnapshotError> {
        let gic_data = self.intc.lock().unwrap().save_snapshot_state();
        Ok(gic_data)
    }

    /// Restore interrupt controller state from snapshot (Linux/aarch64).
    #[cfg(all(target_os = "linux", target_arch = "aarch64", feature = "snapshot"))]
    fn restore_interrupt_controller_state(
        &self,
        data: &[u8],
    ) -> std::result::Result<(), snapshot::SnapshotError> {
        self.intc.lock().unwrap().restore_snapshot_state(data);
        Ok(())
    }

    /// Create a full snapshot of the VM. vCPUs must already be paused.
    #[cfg(all(target_os = "linux", feature = "snapshot"))]
    pub fn create_snapshot(
        &mut self,
        path: &std::path::Path,
    ) -> std::result::Result<(), snapshot::SnapshotError> {
        let mut store = snapshot_store::FsSnapshotStore::new(path);
        self.snapshot_to_store(&mut store)
    }

    /// Restore device and vCPU states from a snapshot.
    ///
    /// This is a shared helper used by both eager restore (drain preload) and
    /// demand-paging restore (UFFD) paths.
    #[cfg(all(target_os = "linux", feature = "snapshot"))]
    fn restore_device_and_vcpu_states(
        &mut self,
        vmstate: snapshot::VmSnapshot,
    ) -> std::result::Result<(), snapshot::SnapshotError> {
        #[cfg(target_arch = "aarch64")]
        if let Some(gic_data) = &vmstate.gic_state {
            self.restore_interrupt_controller_state(gic_data)?;
        }

        #[cfg(target_arch = "x86_64")]
        if let Some(data) = &vmstate.vm_state {
            let state: vstate::VmState = bincode::deserialize(data)
                .map_err(|e| snapshot::SnapshotError::Deserialize(e.to_string()))?;
            self.vm.restore_state(&state).map_err(|e| {
                snapshot::SnapshotError::Deserialize(format!("Failed to restore VM state: {e}"))
            })?;
        }

        self.mmio_device_manager
            .restore_all_device_states(&vmstate.device_states)
            .map_err(|e| {
                snapshot::SnapshotError::Deserialize(format!(
                    "Failed to restore device states: {e}"
                ))
            })?;

        #[cfg(target_arch = "x86_64")]
        {
            self.pio_device_manager
                .restore_all_device_states(&vmstate.device_states)
                .map_err(|e| {
                    snapshot::SnapshotError::Deserialize(format!(
                        "Failed to restore PortIO device states: {e}"
                    ))
                })?;
        }

        self.mmio_device_manager
            .complete_all_device_restores()
            .map_err(|e| {
                snapshot::SnapshotError::Deserialize(format!(
                    "Failed to complete device restores: {e}"
                ))
            })?;
        self.mmio_device_manager.resume_all_device_workers();

        // Write the new GUID to guest memory before vCPU state restore.
        // The GUID must be visible when the guest reads it after the interrupt.
        #[cfg(any(target_arch = "x86_64", target_arch = "aarch64"))]
        let vmgenid_guid_updated = if let Some(ref mut vmgenid) = self.vmgenid {
            let (old, new) = vmgenid.update_guid(&self.guest_memory).map_err(|e| {
                snapshot::SnapshotError::Deserialize(format!("vmgenid: failed to update GUID: {e}"))
            })?;
            log::info!(
                "vmgenid: updated GUID from {:02x?} to {:02x?}",
                &old[..4],
                &new[..4]
            );
            true
        } else {
            false
        };

        self.restore_vcpu_states(vmstate.vcpu_states).map_err(|e| {
            snapshot::SnapshotError::Deserialize(format!("Failed to restore vCPU states: {e}"))
        })?;

        // Signal the vmgenid interrupt AFTER vCPU state restore. KVM_SET_LAPIC
        // overwrites the LAPIC IRR, so any interrupt injected before that
        // would be lost.
        //
        // Use the synchronous KVM_IRQ_LINE ioctl instead of the eventfd/irqfd
        // path (signal_interrupt). The irqfd mechanism processes events
        // asynchronously via a kernel workqueue, so there is a race between
        // the irqfd worker injecting the interrupt and resume_vcpus() making
        // the vCPU enter KVM_RUN. When the vCPU wins the race, the guest
        // runs without seeing the VMGENID change, producing identical CSPRNG
        // output across VM clones. KVM_IRQ_LINE is synchronous: the interrupt
        // is in the LAPIC before this call returns.
        #[cfg(any(target_arch = "x86_64", target_arch = "aarch64"))]
        if vmgenid_guid_updated {
            if let Some(ref vmgenid) = self.vmgenid {
                let irq = vmgenid.irq();
                self.vm.fd().set_irq_line(irq, true).map_err(|e| {
                    snapshot::SnapshotError::Deserialize(format!(
                        "vmgenid: KVM_IRQ_LINE assert failed (irq {irq}): {e}"
                    ))
                })?;
                self.vm.fd().set_irq_line(irq, false).map_err(|e| {
                    snapshot::SnapshotError::Deserialize(format!(
                        "vmgenid: KVM_IRQ_LINE deassert failed (irq {irq}): {e}"
                    ))
                })?;
            }
        }

        Ok(())
    }

    /// Restore a full snapshot into the running VM. vCPUs must already be paused.
    #[cfg(all(target_os = "linux", feature = "snapshot"))]
    pub fn restore_snapshot(
        &mut self,
        path: &std::path::Path,
    ) -> std::result::Result<(), snapshot::SnapshotError> {
        let vmstate = snapshot::load_vmstate(&path.join("vmstate"))?;
        snapshot::validate_header_for_vm(
            &vmstate.header,
            &self.guest_memory,
            self.vcpus_handles.len(),
            self.nested_enabled,
        )?;

        self.mmio_device_manager
            .quiesce_all_device_workers(snapshot::SNAPSHOT_QUIESCE_TIMEOUT)
            .map_err(|e| {
                snapshot::SnapshotError::Deserialize(format!(
                    "Failed to quiesce device workers before restore: {e}"
                ))
            })?;

        snapshot::load_memory(&self.guest_memory, &path.join("memory"))?;

        self.restore_device_and_vcpu_states(vmstate)?;
        Ok(())
    }

    /// Restore a full snapshot using a SnapshotStore. vCPUs must already be paused.
    /// This drains the preload stream to populate memory (eager restore).
    #[cfg(all(target_os = "linux", feature = "snapshot"))]
    pub fn restore_from_store(
        &mut self,
        vmstate_bytes: Vec<u8>,
        mut store: Box<dyn snapshot_store::SnapshotStore>,
        rt: &tokio::runtime::Runtime,
    ) -> std::result::Result<(), snapshot::SnapshotError> {
        // Deserialize vmstate
        let vmstate: snapshot::VmSnapshot = bincode_next::decode_from_slice(&vmstate_bytes, bincode_next::config::standard().with_limit::<{ snapshot::VMSTATE_MAX_SIZE as usize }>())
            .map(|(val, _)| val)
            .map_err(|e| snapshot::SnapshotError::Deserialize(e.to_string()))?;

        snapshot::validate_header_for_vm(
            &vmstate.header,
            &self.guest_memory,
            self.vcpus_handles.len(),
            self.nested_enabled,
        )?;

        self.mmio_device_manager
            .quiesce_all_device_workers(snapshot::SNAPSHOT_QUIESCE_TIMEOUT)
            .map_err(|e| {
                snapshot::SnapshotError::Deserialize(format!(
                    "Failed to quiesce device workers before restore: {e}"
                ))
            })?;

        // Extract excluded pages from vmstate and configure store
        let excluded_pages = vmstate.excluded_pages.clone();
        if !excluded_pages.is_empty() {
            store.set_excluded_pages(excluded_pages.clone());
        }

        // Drain preload stream to populate memory (eager restore)
        let regions = snapshot::ram_layout(&self.guest_memory);

        rt.block_on(async {
            use futures::stream::StreamExt;
            use vm_memory::{Bytes, GuestAddress};

            let mut preload_stream = store.preload(regions);
            while let Some(result) = preload_stream.next().await {
                let (chunk_addr, chunk_data) = result.map_err(|e| {
                    snapshot::SnapshotError::Deserialize(format!("Failed to preload chunk: {e}"))
                })?;
                // Write chunk to guest memory at the specified address
                self.guest_memory
                    .write_slice(&chunk_data, GuestAddress(chunk_addr))
                    .map_err(|e| {
                        snapshot::SnapshotError::Deserialize(format!(
                            "Failed to write chunk at 0x{:x}: {e}",
                            chunk_addr
                        ))
                    })?;
            }
            Ok::<(), snapshot::SnapshotError>(())
        })?;

        // After eager preload completes, zero-fill excluded pages
        if !excluded_pages.is_empty() {
            snapshot::apply_reclaimed_pages(&self.guest_memory, &excluded_pages)?;
        }

        self.restore_device_and_vcpu_states(vmstate)
    }

    /// Restore a full snapshot using UFFD for demand paging.
    ///
    /// When the `uffd` feature is enabled, this method:
    /// 1. Deserializes and validates vmstate (before any UFFD/thread setup)
    /// 2. Creates UFFD handler and registers memory regions
    /// 3. Spawns handler on dedicated thread (preload + fault handling)
    /// 4. Restores device and vCPU states
    /// 5. Signals handler to start fault loop
    ///
    /// The caller must read vmstate from the store before calling this method.
    /// Validation happens before UFFD setup so failures don't leave dangling threads.
    ///
    /// Returns `(handler_thread, shutdown_tx)`. Drop `shutdown_tx` to signal
    /// the UFFD handler to exit its fault loop.
    #[cfg(all(target_os = "linux", feature = "uffd"))]
    pub fn restore_from_store_with_uffd(
        &mut self,
        vmstate_bytes: Vec<u8>,
        mut store: Box<dyn snapshot_store::SnapshotStore>,
        rt: tokio::runtime::Runtime,
    ) -> std::result::Result<
        (
            std::thread::JoinHandle<()>,
            tokio::sync::oneshot::Sender<()>,
        ),
        snapshot::SnapshotError,
    > {
        // Deserialize and validate vmstate BEFORE creating UFFD handler or starting threads.
        // If validation fails, no cleanup is needed.
        let vmstate: snapshot::VmSnapshot = bincode_next::decode_from_slice(&vmstate_bytes, bincode_next::config::standard().with_limit::<{ snapshot::VMSTATE_MAX_SIZE as usize }>())
            .map(|(val, _)| val)
            .map_err(|e| snapshot::SnapshotError::Deserialize(e.to_string()))?;

        snapshot::validate_header_for_vm(
            &vmstate.header,
            &self.guest_memory,
            self.vcpus_handles.len(),
            self.nested_enabled,
        )?;

        self.mmio_device_manager
            .quiesce_all_device_workers(snapshot::SNAPSHOT_QUIESCE_TIMEOUT)
            .map_err(|e| {
                snapshot::SnapshotError::Deserialize(format!(
                    "Failed to quiesce device workers before restore: {e}"
                ))
            })?;

        // Extract excluded pages from vmstate and configure store before converting to Arc
        let excluded_pages = vmstate.excluded_pages.clone();
        if !excluded_pages.is_empty() {
            store.set_excluded_pages(excluded_pages);
        }

        // Get memory regions for UFFD registration (guest_addr, host_addr, size)
        let regions = snapshot::ram_layout(&self.guest_memory);
        let mut uffd_regions = Vec::new();

        use vm_memory::{GuestAddress, GuestMemoryBackend};
        for (guest_addr, size) in regions {
            let host_addr = self
                .guest_memory
                .get_host_address(GuestAddress(guest_addr))
                .map_err(|e| {
                    snapshot::SnapshotError::Deserialize(format!(
                        "failed to get host address for guest region 0x{guest_addr:x}: {e}"
                    ))
                })?;
            uffd_regions.push((guest_addr, host_addr as u64, size));
        }

        // Convert store Box to Arc for sharing with UFFD handler
        let store_arc: Arc<dyn snapshot_store::SnapshotStore> = Arc::from(store);

        let (ready_tx, ready_rx) = tokio::sync::oneshot::channel();
        let (shutdown_tx, shutdown_rx) = tokio::sync::oneshot::channel();

        // Create and spawn UFFD handler on dedicated thread
        let handler = uffd::UffdHandler::new(
            store_arc,
            self.vm_exit.clone(),
            uffd_regions,
            ready_rx,
            shutdown_rx,
        )
        .map_err(|e| {
            snapshot::SnapshotError::Deserialize(format!("Failed to create UFFD handler: {e}"))
        })?;

        let handler_thread = handler.run(rt);

        // Restore device and vCPU states
        self.restore_device_and_vcpu_states(vmstate)?;

        // Signal handler that main thread is ready; handler will start fault loop
        let _ = ready_tx.send(());

        Ok((handler_thread, shutdown_tx))
    }

    /// Sends a resume command to the vcpus.
    pub fn resume_vcpus(&mut self) -> Result<()> {
        for handle in self.vcpus_handles.iter() {
            handle
                .send_event(VcpuEvent::Resume)
                .map_err(Error::VcpuEvent)?;
        }
        for handle in self.vcpus_handles.iter() {
            match handle
                .response_receiver()
                .recv_timeout(Duration::from_millis(1000))
            {
                Ok(VcpuResponse::Resumed) => (),
                _ => return Err(Error::VcpuResume),
            }
        }
        Ok(())
    }

    /// Configures the system for boot.
    pub fn configure_system(
        &self,
        vcpus: &[Vcpu],
        _intc: &IrqChip,
        initrd: &Option<InitrdConfig>,
        _smbios_oem_strings: &Option<Vec<String>>,
    ) -> Result<()> {
        #[cfg(target_arch = "x86_64")]
        {
            let cmdline_len = if cfg!(feature = "tee") {
                arch::x86_64::layout::CMDLINE_SEV_SIZE
            } else {
                self.kernel_cmdline.len() + 1
            };

            arch::x86_64::configure_system(
                &self.guest_memory,
                &self.arch_memory_info,
                vm_memory::GuestAddress(arch::x86_64::layout::CMDLINE_START),
                cmdline_len,
                initrd,
                vcpus.len() as u8,
            )
            .map_err(Error::ConfigureSystem)?;
        }

        #[cfg(target_arch = "aarch64")]
        {
            let vcpu_mpidr = vcpus.iter().map(|cpu| cpu.get_mpidr()).collect();
            fdt::create_fdt(
                &self.guest_memory,
                &self.arch_memory_info,
                vcpu_mpidr,
                self.kernel_cmdline.as_str(),
                self.mmio_device_manager.get_device_info(),
                _intc,
                initrd,
            )
            .map_err(Error::SetupFDT)?;
        }

        #[cfg(target_arch = "aarch64")]
        {
            arch::aarch64::configure_system(
                &self.guest_memory,
                &self.arch_memory_info,
                _smbios_oem_strings,
            )
            .map_err(Error::ConfigureSystem)?;
        }

        #[cfg(target_arch = "riscv64")]
        {
            fdt::create_fdt(
                &self.guest_memory,
                &self.arch_memory_info,
                vcpus.len() as u32,
                self.kernel_cmdline.as_str(),
                self.mmio_device_manager.get_device_info(),
                _intc,
                initrd,
            )
            .map_err(Error::SetupFDT)?;

            arch::riscv64::configure_system(&self.guest_memory, _smbios_oem_strings)
                .map_err(Error::ConfigureSystem)?;
        }

        Ok(())
    }

    /// Returns a reference to the guest memory.
    pub fn guest_memory(&self) -> &GuestMemoryMmap {
        &self.guest_memory
    }

    /// Returns a reference to the arch memory info.
    pub fn arch_memory_info(&self) -> &ArchMemoryInfo {
        &self.arch_memory_info
    }

    /// Create a full snapshot of the VM. vCPUs must already be paused.
    #[cfg(all(target_os = "macos", feature = "snapshot"))]
    pub fn create_snapshot(
        &mut self,
        path: &std::path::Path,
    ) -> std::result::Result<(), snapshot::SnapshotError> {
        let mut store = snapshot_store::FsSnapshotStore::new(path);
        self.snapshot_to_store(&mut store)
    }

    /// Restore a full snapshot into the running VM. vCPUs must already be paused.
    #[cfg(all(target_os = "macos", feature = "snapshot"))]
    pub fn restore_snapshot(
        &mut self,
        path: &std::path::Path,
    ) -> std::result::Result<(), snapshot::SnapshotError> {
        let vmstate = snapshot::load_vmstate(&path.join("vmstate"))?;
        snapshot::validate_header_for_vm(
            &vmstate.header,
            &self.guest_memory,
            self.vcpus_handles.len(),
            self.nested_enabled,
        )?;

        // Quiesce all async device workers before overwriting guest memory.
        // Workers may hold VolatileSliceGuard pointers into guest RAM; if we
        // overwrite memory while they're mid-operation, they'll corrupt the
        // restored state (e.g. writing stale used-ring entries → NETDEV WATCHDOG).
        self.mmio_device_manager
            .quiesce_all_device_workers(snapshot::SNAPSHOT_QUIESCE_TIMEOUT)
            .map_err(|e| {
                snapshot::SnapshotError::Deserialize(format!(
                    "Failed to quiesce device workers before restore: {e}"
                ))
            })?;

        snapshot::load_memory(&self.guest_memory, &path.join("memory"))?;

        // Phase 1: Restore all state without spawning any threads.
        // Device state is deserialized but activate() is deferred.
        if let Some(gic_data) = &vmstate.gic_state {
            self.restore_interrupt_controller_state(gic_data)?;
        }
        self.mmio_device_manager
            .restore_all_device_states(&vmstate.device_states)
            .map_err(|e| {
                snapshot::SnapshotError::Deserialize(format!(
                    "Failed to restore device states: {e}"
                ))
            })?;

        // Phase 2: Now that all state is loaded, activate devices (spawning
        // threads) and kick workers. Threads can safely fire IRQs because
        // interrupt controller state is already in place.
        self.mmio_device_manager
            .complete_all_device_restores()
            .map_err(|e| {
                snapshot::SnapshotError::Deserialize(format!(
                    "Failed to complete device restores: {e}"
                ))
            })?;
        self.mmio_device_manager.resume_all_device_workers();

        let vcpu_states: Vec<hvf::Aarch64VcpuState> = vmstate
            .vcpu_states
            .iter()
            .map(|data| {
                bincode_next::decode_from_slice::<hvf::Aarch64VcpuState, _>(data, bincode_next::config::standard().with_limit::<{ snapshot::VMSTATE_MAX_SIZE as usize }>())
                    .map(|(val, _)| val)
                    .map_err(|e| snapshot::SnapshotError::Deserialize(e.to_string()))
            })
            .collect::<std::result::Result<_, _>>()?;

        self.restore_vcpu_states(vcpu_states).map_err(|e| {
            snapshot::SnapshotError::Deserialize(format!("Failed to restore vCPU states: {e}"))
        })?;
        Ok(())
    }

    /// Enable dirty page tracking. vCPUs must be paused.
    /// After this call, all RAM writes will be tracked via write-protect faults.
    #[cfg(target_os = "macos")]
    pub fn enable_dirty_tracking(&mut self) -> Result<()> {
        use vm_memory::{GuestMemoryBackend, GuestMemoryRegion};

        let mut new_bitmaps = Vec::new();
        let mut ram_regions = Vec::new();
        for region in self.guest_memory.iter() {
            let base = region.start_addr().raw_value();
            let size = region.len();
            new_bitmaps.push(dirty_bitmap::DirtyBitmap::new(base, size));
            ram_regions.push((base, size));

            Vm::protect_memory(base, size, true, false, true).map_err(Error::Vm)?;
        }
        self.dirty_bitmaps = Arc::new(new_bitmaps);

        for handle in self.vcpus_handles.iter() {
            let bitmaps = Arc::clone(&self.dirty_bitmaps);
            let ram_regions_clone = ram_regions.clone();

            let callback: hvf::DirtyCallback = Box::new(move |page_addr| {
                for bitmap in bitmaps.iter() {
                    if bitmap.contains(page_addr) {
                        bitmap.mark_dirty(page_addr);
                        return;
                    }
                }
            });

            let config = crate::vstate::DirtyTrackingConfig {
                ram_regions: ram_regions_clone,
                dirty_callback: callback,
            };

            handle
                .send_event(VcpuEvent::EnableDirtyTracking(Box::new(config)))
                .map_err(Error::VcpuEvent)?;
        }

        self.dirty_tracking_enabled = true;

        Ok(())
    }

    /// Disable dirty page tracking. vCPUs must be paused.
    #[cfg(target_os = "macos")]
    pub fn disable_dirty_tracking(&mut self) -> Result<()> {
        use vm_memory::{GuestMemoryBackend, GuestMemoryRegion};

        for region in self.guest_memory.iter() {
            let base = region.start_addr().raw_value();
            let size = region.len();
            Vm::protect_memory(base, size, true, true, true).map_err(Error::Vm)?;
        }

        for handle in self.vcpus_handles.iter() {
            handle
                .send_event(VcpuEvent::DisableDirtyTracking)
                .map_err(Error::VcpuEvent)?;
        }

        self.dirty_bitmaps = Arc::new(Vec::new());
        Ok(())
    }

    /// Create an incremental snapshot (dirty pages only). vCPUs must be paused.
    #[cfg(all(target_os = "macos", feature = "snapshot"))]
    pub fn create_incremental_snapshot(
        &mut self,
        path: &std::path::Path,
    ) -> std::result::Result<(), snapshot::SnapshotError> {
        let mut store = snapshot_store::FsSnapshotStore::new(path);
        self.incremental_snapshot_to_store(&mut store)
    }

    /// Restore an incremental snapshot. vCPUs must already be paused.
    #[cfg(all(target_os = "macos", feature = "snapshot"))]
    pub fn restore_incremental_snapshot(
        &mut self,
        path: &std::path::Path,
    ) -> std::result::Result<(), snapshot::SnapshotError> {
        let incremental = snapshot::load_incremental_snapshot(&path.join("vmstate"))?;
        snapshot::validate_header_for_vm(
            &incremental.header,
            &self.guest_memory,
            self.vcpus_handles.len(),
            self.nested_enabled,
        )?;

        // Quiesce all async device workers before overwriting guest memory.
        // Same race as restore_snapshot: workers may hold raw pointers into
        // guest RAM during in-flight I/O.
        self.mmio_device_manager
            .quiesce_all_device_workers(snapshot::SNAPSHOT_QUIESCE_TIMEOUT)
            .map_err(|e| {
                snapshot::SnapshotError::Deserialize(format!(
                    "Failed to quiesce device workers before restore: {e}"
                ))
            })?;

        snapshot::apply_dirty_pages(&self.guest_memory, &incremental.dirty_pages)?;

        // Phase 1: Restore all state without spawning any threads.
        if let Some(gic_data) = &incremental.gic_state {
            self.restore_interrupt_controller_state(gic_data)?;
        }
        self.mmio_device_manager
            .restore_all_device_states(&incremental.device_states)
            .map_err(|e| {
                snapshot::SnapshotError::Deserialize(format!(
                    "Failed to restore device states: {e}"
                ))
            })?;

        // Phase 2: Activate devices (if needed) and kick workers.
        self.mmio_device_manager
            .complete_all_device_restores()
            .map_err(|e| {
                snapshot::SnapshotError::Deserialize(format!(
                    "Failed to complete device restores: {e}"
                ))
            })?;
        self.mmio_device_manager.resume_all_device_workers();

        let vcpu_states: Vec<hvf::Aarch64VcpuState> = incremental
            .vcpu_states
            .iter()
            .map(|data| {
                bincode_next::decode_from_slice::<hvf::Aarch64VcpuState, _>(data, bincode_next::config::standard().with_limit::<{ snapshot::VMSTATE_MAX_SIZE as usize }>())
                    .map(|(val, _)| val)
                    .map_err(|e| snapshot::SnapshotError::Deserialize(e.to_string()))
            })
            .collect::<std::result::Result<_, _>>()?;

        self.restore_vcpu_states(vcpu_states).map_err(|e| {
            snapshot::SnapshotError::Deserialize(format!("Failed to restore vCPU states: {e}"))
        })?;
        Ok(())
    }

    /// Enable dirty page tracking via KVM dirty log. vCPUs must be paused.
    #[cfg(all(target_os = "linux", feature = "snapshot"))]
    pub fn enable_dirty_tracking(&mut self) -> Result<()> {
        use kvm_bindings::{kvm_userspace_memory_region, KVM_MEM_LOG_DIRTY_PAGES};

        for &(slot, guest_addr, size, host_addr) in &self.vm.mem_slots {
            let region = kvm_userspace_memory_region {
                slot,
                guest_phys_addr: guest_addr,
                memory_size: size,
                userspace_addr: host_addr,
                flags: KVM_MEM_LOG_DIRTY_PAGES,
            };
            unsafe {
                self.vm
                    .fd()
                    .set_user_memory_region(region)
                    .map_err(|e| Error::Vm(vstate::Error::SetUserMemoryRegion(e)))?;
            }
        }
        self.dirty_tracking_enabled = true;
        Ok(())
    }

    /// Collect dirty pages from KVM dirty log.
    #[cfg(all(target_os = "linux", feature = "snapshot"))]
    fn collect_dirty_pages(
        &self,
    ) -> std::result::Result<Vec<snapshot::DirtyPage>, snapshot::SnapshotError> {
        let page_size = 4096u64;
        let mut pages = Vec::new();
        for &(slot, guest_addr, size, _) in &self.vm.mem_slots {
            let bitmap = self
                .vm
                .fd()
                .get_dirty_log(slot, size as usize)
                .map_err(|e| {
                    snapshot::SnapshotError::Serialize(format!(
                        "Failed to get dirty log for slot {slot}: {e}"
                    ))
                })?;
            for (word_idx, &word) in bitmap.iter().enumerate() {
                if word == 0 {
                    continue;
                }
                for bit in 0..64u32 {
                    if (word >> bit) & 1 != 0 {
                        let page_idx = word_idx as u64 * 64 + bit as u64;
                        let addr = guest_addr + page_idx * page_size;
                        let vhp =
                            get_validated_host_ptr(&self.guest_memory, addr).ok_or_else(|| {
                                snapshot::SnapshotError::Serialize(format!(
                                    "Invalid guest address for dirty page 0x{addr:x}"
                                ))
                            })?;
                        let data = vhp.as_slice(page_size as usize).map_err(|e| {
                            snapshot::SnapshotError::Serialize(format!(
                                "Dirty page slice out of bounds at 0x{addr:x}: {e}"
                            ))
                        })?;
                        pages.push(snapshot::DirtyPage {
                            guest_addr: addr,
                            data: data.to_vec(),
                        });
                    }
                }
            }
        }
        Ok(pages)
    }

    /// Create an incremental snapshot (dirty pages only). vCPUs must be paused.
    #[cfg(all(target_os = "linux", feature = "snapshot"))]
    pub fn create_incremental_snapshot(
        &mut self,
        path: &std::path::Path,
    ) -> std::result::Result<(), snapshot::SnapshotError> {
        let mut store = snapshot_store::FsSnapshotStore::new(path);
        self.incremental_snapshot_to_store(&mut store)
    }

    /// Restore an incremental snapshot. vCPUs must already be paused.
    #[cfg(all(target_os = "linux", feature = "snapshot"))]
    pub fn restore_incremental_snapshot(
        &mut self,
        path: &std::path::Path,
    ) -> std::result::Result<(), snapshot::SnapshotError> {
        let incremental = snapshot::load_incremental_snapshot(&path.join("vmstate"))?;
        snapshot::validate_header_for_vm(
            &incremental.header,
            &self.guest_memory,
            self.vcpus_handles.len(),
            self.nested_enabled,
        )?;

        self.mmio_device_manager
            .quiesce_all_device_workers(snapshot::SNAPSHOT_QUIESCE_TIMEOUT)
            .map_err(|e| {
                snapshot::SnapshotError::Deserialize(format!(
                    "Failed to quiesce device workers before restore: {e}"
                ))
            })?;

        snapshot::apply_dirty_pages(&self.guest_memory, &incremental.dirty_pages)?;

        // Zero-fill reclaimed pages (Task 7: AC2.6)
        if !incremental.reclaimed_pages.is_empty() {
            snapshot::apply_reclaimed_pages(&self.guest_memory, &incremental.reclaimed_pages)?;
        }

        // Reuse shared helper for device/vCPU state restoration
        let vmstate = snapshot::VmSnapshot {
            header: incremental.header,
            vcpu_states: incremental.vcpu_states,
            device_states: incremental.device_states,
            gic_state: incremental.gic_state,
            vm_state: incremental.vm_state,
            excluded_pages: Vec::new(),
        };
        self.restore_device_and_vcpu_states(vmstate)?;
        Ok(())
    }

    /// Private helper to dump guest memory and write to store, then close.
    /// Extracted to reduce code duplication between Linux and macOS snapshot_to_store.
    ///
    /// # Arguments
    /// * `store` - The snapshot store to write to (mutable to set ram_regions and excluded_pages)
    /// * `vmstate_data` - Serialized VmSnapshot (including excluded_pages)
    /// * `excluded_pages` - Set of guest page addresses to skip (balloon-reclaimed pages)
    #[cfg(feature = "snapshot")]
    fn dump_memory_to_store(
        &self,
        store: &mut dyn snapshot_store::SnapshotStore,
        vmstate_data: Vec<u8>,
        excluded_pages: &std::collections::HashSet<u64>,
    ) -> std::result::Result<(), snapshot::SnapshotError> {
        use vm_memory::{Address, GuestMemoryBackend, GuestMemoryRegion};

        // Set RAM regions and excluded pages on the store for proper sparse file layout
        store.set_ram_regions(snapshot::ram_layout(&self.guest_memory));
        store.set_excluded_pages(excluded_pages.iter().copied().collect());

        // Serialize vmstate
        futures::executor::block_on(store.write_vmstate(vmstate_data))
            .map_err(snapshot::SnapshotError::Io)?;

        // Dump memory and write pages, skipping excluded pages
        let mut pages = Vec::new();
        for region in self.guest_memory.iter() {
            let region_start = region.start_addr().raw_value();
            let len = region.len() as usize;

            // Iterate through the region at 4KB page granularity
            let mut chunk_start = region_start;
            let chunk_end = region_start + len as u64;
            while chunk_start < chunk_end {
                if !excluded_pages.contains(&chunk_start) {
                    // Page is not excluded, include it
                    let vhp = get_validated_host_ptr(&self.guest_memory, chunk_start).ok_or_else(
                        || {
                            snapshot::SnapshotError::Serialize(format!(
                                "Invalid guest address at {chunk_start:#x}"
                            ))
                        },
                    )?;
                    let page_data = vhp.as_slice(4096).map_err(|e| {
                        snapshot::SnapshotError::Serialize(format!(
                            "Page slice out of bounds at {chunk_start:#x}: {e}"
                        ))
                    })?;
                    pages.push((chunk_start, page_data.to_vec()));
                }
                chunk_start += 4096;
            }
        }

        futures::executor::block_on(store.write_pages(pages))
            .map_err(snapshot::SnapshotError::Io)?;

        // Sync all data
        futures::executor::block_on(store.close()).map_err(snapshot::SnapshotError::Io)?;

        Ok(())
    }

    /// Create a full snapshot using a SnapshotStore. vCPUs must already be paused.
    #[cfg(all(target_os = "linux", feature = "snapshot"))]
    pub fn snapshot_to_store(
        &mut self,
        store: &mut dyn snapshot_store::SnapshotStore,
    ) -> std::result::Result<(), snapshot::SnapshotError> {
        use std::collections::HashSet;

        // Reuse the existing full snapshot creation, but write to store instead
        let mut device_states = self
            .mmio_device_manager
            .save_all_device_states()
            .map_err(|e| {
                snapshot::SnapshotError::Serialize(format!("Failed to save device states: {e}"))
            })?;

        #[cfg(target_arch = "x86_64")]
        {
            let pio_states = self
                .pio_device_manager
                .save_all_device_states()
                .map_err(|e| {
                    snapshot::SnapshotError::Serialize(format!(
                        "Failed to save PortIO device states: {e}"
                    ))
                })?;
            device_states.extend(pio_states);
        }

        let vcpu_states = self.save_vcpu_states().map_err(|e| {
            snapshot::SnapshotError::Serialize(format!("Failed to save vCPU states: {e}"))
        })?;

        #[cfg(target_arch = "aarch64")]
        let gic_state = self.save_interrupt_controller_state()?;
        #[cfg(not(target_arch = "aarch64"))]
        let gic_state = None;

        #[cfg(target_arch = "x86_64")]
        let vm_state = Some(
            bincode::serialize(&self.vm.save_state().map_err(|e| {
                snapshot::SnapshotError::Serialize(format!("Failed to save VM state: {e}"))
            })?)
            .map_err(|e| snapshot::SnapshotError::Serialize(e.to_string()))?,
        );
        #[cfg(not(target_arch = "x86_64"))]
        let vm_state = None;

        // Query balloon device for reclaimed pages and build excluded set
        #[cfg(not(feature = "tee"))]
        let (excluded_pages, excluded_pages_vec) = {
            let mut excluded = HashSet::new();
            let mut excluded_vec = Vec::new();

            if let Some(balloon) = self.balloon.as_ref() {
                let balloon_guard = balloon.lock().unwrap();
                let (inflated_bitmap, reported_free_bitmap) = balloon_guard.reclaimed_bitmaps();

                // Always exclude inflated pages (AC2.3)
                if let Some(bitmap) = inflated_bitmap {
                    for pfn in bitmap.iter_set_pages() {
                        let guest_addr = (pfn as u64) * 4096;
                        excluded.insert(guest_addr);
                        excluded_vec.push(guest_addr);
                    }
                }

                // Verify and exclude reported-free pages (AC2.4, AC2.7)
                if let Some(bitmap) = reported_free_bitmap {
                    for pfn in bitmap.iter_set_pages() {
                        let guest_addr = (pfn as u64) * 4096;

                        // Check if page is resident via mincore
                        let vhp = get_validated_host_ptr(&self.guest_memory, guest_addr);

                        let should_exclude = if let Some(vhp) = vhp {
                            match mincore_check(vhp.as_ptr(), 4096) {
                                Ok(residency) => {
                                    if residency.is_empty() || !residency[0] {
                                        // Non-resident page: definitely zeros
                                        true
                                    } else {
                                        // Page is resident: check if it's all zeros
                                        // If all-zero, exclude; if non-zero, don't exclude (guest reused)
                                        match vhp.as_slice(4096) {
                                            Ok(slice) => slice.iter().all(|&b| b == 0),
                                            Err(_) => false,
                                        }
                                    }
                                }
                                Err(_) => {
                                    // mincore failed; conservatively include the page
                                    false
                                }
                            }
                        } else {
                            // Failed to get host address or region; conservatively include
                            false
                        };

                        if should_exclude {
                            excluded.insert(guest_addr);
                            excluded_vec.push(guest_addr);
                        }
                    }
                }
            }

            (excluded, excluded_vec)
        };

        #[cfg(feature = "tee")]
        let (excluded_pages, excluded_pages_vec) = (std::collections::HashSet::new(), Vec::new());

        // Create VmSnapshot
        let vm_snapshot = snapshot::VmSnapshot {
            header: snapshot::SnapshotHeader {
                magic: snapshot::SNAPSHOT_MAGIC,
                version: snapshot::SNAPSHOT_VERSION,
                vcpu_count: vcpu_states.len() as u32,
                ram_regions: snapshot::ram_layout(&self.guest_memory),
                // Use nested_enabled from Vmm; this fixes the hardcoded false from the previous implementation
                nested_enabled: self.nested_enabled,
            },
            vcpu_states,
            device_states,
            gic_state,
            vm_state,
            excluded_pages: excluded_pages_vec,
        };

        // Serialize vmstate
        let vmstate_data = bincode_next::encode_to_vec(&vm_snapshot, bincode_next::config::standard())
            .map_err(|e| snapshot::SnapshotError::Serialize(e.to_string()))?;

        // Use helper to dump memory and write to store
        self.dump_memory_to_store(store, vmstate_data, &excluded_pages)
    }

    /// Create a full snapshot using a SnapshotStore. vCPUs must already be paused.
    #[cfg(all(target_os = "macos", feature = "snapshot"))]
    pub fn snapshot_to_store(
        &mut self,
        store: &mut dyn snapshot_store::SnapshotStore,
    ) -> std::result::Result<(), snapshot::SnapshotError> {
        // macOS/aarch64 version - no vm_state, no PortIO
        let device_states = self
            .mmio_device_manager
            .save_all_device_states()
            .map_err(|e| {
                snapshot::SnapshotError::Serialize(format!("Failed to save device states: {e}"))
            })?;

        let vcpu_states = self.save_vcpu_states().map_err(|e| {
            snapshot::SnapshotError::Serialize(format!("Failed to save vCPU states: {e}"))
        })?;

        let serialized_vcpu_states: Vec<Vec<u8>> = vcpu_states
            .iter()
            .map(|s| {
                bincode_next::encode_to_vec(s, bincode_next::config::standard()).map_err(|e| snapshot::SnapshotError::Serialize(e.to_string()))
            })
            .collect::<std::result::Result<_, _>>()?;

        let gic_state = self.save_interrupt_controller_state()?;

        // Create VmSnapshot
        let vm_snapshot = snapshot::VmSnapshot {
            header: snapshot::SnapshotHeader {
                magic: snapshot::SNAPSHOT_MAGIC,
                version: snapshot::SNAPSHOT_VERSION,
                vcpu_count: serialized_vcpu_states.len() as u32,
                ram_regions: snapshot::ram_layout(&self.guest_memory),
                // Use nested_enabled from Vmm; this fixes the hardcoded false from the previous implementation
                nested_enabled: self.nested_enabled,
            },
            vcpu_states: serialized_vcpu_states,
            device_states,
            gic_state,
            vm_state: None,
            excluded_pages: Vec::new(),
        };

        // Serialize vmstate
        let vmstate_data = bincode_next::encode_to_vec(&vm_snapshot, bincode_next::config::standard())
            .map_err(|e| snapshot::SnapshotError::Serialize(e.to_string()))?;

        // Use helper to dump memory and write to store
        // macOS has no balloon support, so excluded_pages is always empty
        let excluded_pages = std::collections::HashSet::new();
        self.dump_memory_to_store(store, vmstate_data, &excluded_pages)
    }

    /// Create an incremental snapshot using a SnapshotStore. vCPUs must already be paused.
    #[cfg(all(target_os = "linux", feature = "snapshot"))]
    pub fn incremental_snapshot_to_store(
        &mut self,
        store: &mut dyn snapshot_store::SnapshotStore,
    ) -> std::result::Result<(), snapshot::SnapshotError> {
        if !self.dirty_tracking_enabled {
            return Err(snapshot::SnapshotError::DirtyTrackingNotEnabled);
        }

        let mut device_states = self
            .mmio_device_manager
            .save_all_device_states()
            .map_err(|e| {
                snapshot::SnapshotError::Serialize(format!("Failed to save device states: {e}"))
            })?;

        #[cfg(target_arch = "x86_64")]
        {
            let pio_states = self
                .pio_device_manager
                .save_all_device_states()
                .map_err(|e| {
                    snapshot::SnapshotError::Serialize(format!(
                        "Failed to save PortIO device states: {e}"
                    ))
                })?;
            device_states.extend(pio_states);
        }

        let vcpu_states = self.save_vcpu_states().map_err(|e| {
            snapshot::SnapshotError::Serialize(format!("Failed to save vCPU states: {e}"))
        })?;

        #[cfg(target_arch = "aarch64")]
        let gic_state = self.save_interrupt_controller_state()?;
        #[cfg(not(target_arch = "aarch64"))]
        let gic_state = None;

        #[cfg(target_arch = "x86_64")]
        let vm_state = Some(
            bincode::serialize(&self.vm.save_state().map_err(|e| {
                snapshot::SnapshotError::Serialize(format!("Failed to save VM state: {e}"))
            })?)
            .map_err(|e| snapshot::SnapshotError::Serialize(e.to_string()))?,
        );
        #[cfg(not(target_arch = "x86_64"))]
        let vm_state = None;

        let mut dirty_pages = self.collect_dirty_pages()?;

        // Mark virtio used ring pages dirty (host writes not tracked by KVM)
        let used_ring_ranges = self.mmio_device_manager.get_virtio_used_ring_ranges();
        for (page_addr, page_size) in &used_ring_ranges {
            // Check if this page is already in the dirty set
            if !dirty_pages.iter().any(|p| p.guest_addr == *page_addr) {
                let vhp =
                    get_validated_host_ptr(&self.guest_memory, *page_addr).ok_or_else(|| {
                        snapshot::SnapshotError::Serialize(format!(
                            "Invalid guest address for used ring page 0x{page_addr:x}"
                        ))
                    })?;
                let data = vhp.as_slice(*page_size as usize).map_err(|e| {
                    snapshot::SnapshotError::Serialize(format!(
                        "Used ring page slice out of bounds at 0x{page_addr:x}: {e}"
                    ))
                })?;
                dirty_pages.push(snapshot::DirtyPage {
                    guest_addr: *page_addr,
                    data: data.to_vec(),
                });
            }
        }

        // Build reclaimed_pages from balloon bitmaps (Task 6: AC2.5)
        #[cfg(not(feature = "tee"))]
        let (dirty_pages, reclaimed_pages) = {
            let mut reclaimed = Vec::new();
            let mut dirty_set: std::collections::HashSet<u64> =
                dirty_pages.iter().map(|p| p.guest_addr).collect();

            if let Some(balloon) = self.balloon.as_ref() {
                let balloon_guard = balloon.lock().unwrap();
                let (inflated_bitmap, reported_free_bitmap) = balloon_guard.reclaimed_bitmaps();

                // Dirty pages that are inflated: remove from dirty_pages and add to reclaimed
                if let Some(bitmap) = inflated_bitmap {
                    for pfn in bitmap.iter_set_pages() {
                        let guest_addr = (pfn as u64) * 4096;
                        if dirty_set.contains(&guest_addr) {
                            reclaimed.push(guest_addr);
                            dirty_set.remove(&guest_addr);
                        }
                    }
                }

                // Pages in reported-free bitmap that are verified-free and not in dirty_pages
                if let Some(bitmap) = reported_free_bitmap {
                    for pfn in bitmap.iter_set_pages() {
                        let guest_addr = (pfn as u64) * 4096;
                        if !dirty_set.contains(&guest_addr) {
                            // Verify it's reported-free (non-resident or all-zeros)
                            let vhp = get_validated_host_ptr(&self.guest_memory, guest_addr);

                            let should_reclaim = if let Some(vhp) = vhp {
                                match mincore_check(vhp.as_ptr(), 4096) {
                                    Ok(residency) => {
                                        if residency.is_empty() || !residency[0] {
                                            // Non-resident page: definitely zeros
                                            true
                                        } else {
                                            // Page is resident: check if it's all zeros
                                            match vhp.as_slice(4096) {
                                                Ok(slice) => slice.iter().all(|&b| b == 0),
                                                Err(_) => false,
                                            }
                                        }
                                    }
                                    Err(_) => {
                                        // mincore failed; conservatively skip this page
                                        false
                                    }
                                }
                            } else {
                                // Failed to get host address or region; conservatively skip
                                false
                            };

                            if should_reclaim {
                                reclaimed.push(guest_addr);
                            }
                        }
                    }
                }
            }

            // Rebuild dirty_pages without reclaimed entries
            let filtered_dirty_pages = dirty_pages
                .into_iter()
                .filter(|p| dirty_set.contains(&p.guest_addr))
                .collect::<Vec<_>>();

            (filtered_dirty_pages, reclaimed)
        };

        #[cfg(feature = "tee")]
        let reclaimed_pages = Vec::new();

        let incremental = snapshot::IncrementalSnapshot {
            header: snapshot::SnapshotHeader {
                magic: snapshot::SNAPSHOT_MAGIC,
                version: snapshot::SNAPSHOT_VERSION,
                vcpu_count: vcpu_states.len() as u32,
                ram_regions: snapshot::ram_layout(&self.guest_memory),
                nested_enabled: self.nested_enabled,
            },
            vcpu_states,
            device_states,
            dirty_pages,
            gic_state,
            vm_state,
            reclaimed_pages,
        };

        // Serialize incremental snapshot
        let vmstate_data = bincode_next::encode_to_vec(&incremental, bincode_next::config::standard())
            .map_err(|e| snapshot::SnapshotError::Serialize(e.to_string()))?;

        // Write vmstate via store (blocking on async)
        futures::executor::block_on(store.write_vmstate(vmstate_data))
            .map_err(snapshot::SnapshotError::Io)?;

        // For incremental snapshots, dirty pages are in the vmstate blob, so no memory file
        futures::executor::block_on(store.write_pages(Vec::new()))
            .map_err(snapshot::SnapshotError::Io)?;

        // Sync all data
        futures::executor::block_on(store.close()).map_err(snapshot::SnapshotError::Io)?;

        Ok(())
    }

    /// Create an incremental snapshot using a SnapshotStore. vCPUs must already be paused.
    #[cfg(all(target_os = "macos", feature = "snapshot"))]
    pub fn incremental_snapshot_to_store(
        &mut self,
        store: &dyn snapshot_store::SnapshotStore,
    ) -> std::result::Result<(), snapshot::SnapshotError> {
        use vm_memory::{Address, GuestAddress, GuestMemoryBackend, GuestMemoryRegion};

        if !self.dirty_tracking_enabled {
            return Err(snapshot::SnapshotError::DirtyTrackingNotEnabled);
        }

        // Save device state before vCPU state (Firecracker convention: device
        // save may trigger interrupts that should be captured in vCPU state).
        let device_states = self
            .mmio_device_manager
            .save_all_device_states()
            .map_err(|e| {
                snapshot::SnapshotError::Serialize(format!("Failed to save device states: {e}"))
            })?;

        let vcpu_states = self.save_vcpu_states().map_err(|e| {
            snapshot::SnapshotError::Serialize(format!("Failed to save vCPU states: {e}"))
        })?;

        let serialized_vcpu_states: Vec<Vec<u8>> = vcpu_states
            .iter()
            .map(|s| {
                bincode_next::encode_to_vec(s, bincode_next::config::standard()).map_err(|e| snapshot::SnapshotError::Serialize(e.to_string()))
            })
            .collect::<std::result::Result<_, _>>()?;

        let gic_state = self.save_interrupt_controller_state()?;

        // Mark virtio used ring pages dirty (host writes not tracked by memory protection)
        let used_ring_ranges = self.mmio_device_manager.get_virtio_used_ring_ranges();
        for (page_addr, _) in &used_ring_ranges {
            for bitmap in &self.dirty_bitmaps {
                bitmap.mark_dirty(*page_addr);
            }
        }

        let mut dirty_pages = Vec::new();
        for bitmap in &self.dirty_bitmaps {
            let dirty_addrs = bitmap.drain_dirty_pages();
            for addr in dirty_addrs {
                let vhp = get_validated_host_ptr(&self.guest_memory, addr).ok_or_else(|| {
                    snapshot::SnapshotError::Serialize(format!(
                        "Invalid guest address for dirty page 0x{addr:x}"
                    ))
                })?;
                let page_data = vhp
                    .as_slice(dirty_bitmap::PAGE_SIZE as usize)
                    .map_err(|e| {
                        snapshot::SnapshotError::Serialize(format!(
                            "Dirty page slice out of bounds at 0x{addr:x}: {e}"
                        ))
                    })?;
                dirty_pages.push(snapshot::DirtyPage {
                    guest_addr: addr,
                    data: page_data.to_vec(),
                });
            }
        }

        for region in self.guest_memory.iter() {
            let base = region.start_addr().raw_value();
            let size = region.len();
            Vm::protect_memory(base, size, true, false, true).map_err(|e| {
                snapshot::SnapshotError::Io(std::io::Error::new(
                    std::io::ErrorKind::Other,
                    format!("{e}"),
                ))
            })?;
        }

        let incremental = snapshot::IncrementalSnapshot {
            header: snapshot::SnapshotHeader {
                magic: snapshot::SNAPSHOT_MAGIC,
                version: snapshot::SNAPSHOT_VERSION,
                vcpu_count: serialized_vcpu_states.len() as u32,
                ram_regions: snapshot::ram_layout(&self.guest_memory),
                nested_enabled: self.nested_enabled,
            },
            vcpu_states: serialized_vcpu_states,
            device_states,
            dirty_pages,
            gic_state,
            vm_state: None,
            reclaimed_pages: Vec::new(),
        };

        // Serialize incremental snapshot
        let vmstate_data = bincode_next::encode_to_vec(&incremental, bincode_next::config::standard())
            .map_err(|e| snapshot::SnapshotError::Serialize(e.to_string()))?;

        // Write vmstate via store (blocking on async)
        futures::executor::block_on(store.write_vmstate(vmstate_data))
            .map_err(snapshot::SnapshotError::Io)?;

        // For incremental snapshots, dirty pages are in the vmstate blob, so no memory file
        futures::executor::block_on(store.write_pages(Vec::new()))
            .map_err(snapshot::SnapshotError::Io)?;

        // Sync all data
        futures::executor::block_on(store.close()).map_err(snapshot::SnapshotError::Io)?;

        Ok(())
    }

    /// Injects CTRL+ALT+DEL keystroke combo in the i8042 device.
    #[cfg(target_arch = "x86_64")]
    pub fn send_ctrl_alt_del(&mut self) -> Result<()> {
        self.pio_device_manager
            .i8042
            .lock()
            .expect("i8042 lock was poisoned")
            .trigger_ctrl_alt_del()
            .map_err(Error::I8042Error)
    }

    /// Registers an exit observer that will be called when the VM exits.
    pub fn register_exit_observer(&mut self, observer: Arc<Mutex<dyn VmmExitObserver>>) {
        self.exit_observers.push(observer);
    }

    /// Waits for all vCPUs to exit and stores exit information in shared state.
    pub fn stop(&mut self, vm_exit: crate::vm_exit::VmExit) {
        info!("Vmm is stopping: {vm_exit:?}");

        // Run exit observers first (AC3.1)
        for observer in &self.exit_observers {
            observer
                .lock()
                .expect("Poisoned mutex for exit observer")
                .on_vmm_exit();
        }

        // Signal vCPU threads to exit their blocking state (AC3.2)
        self.vcpu_exit_flag.store(true, Ordering::Release);

        // Store the exit reason for Context::run() to read
        *self.vm_exit.lock().expect("Poisoned vm_exit lock") = Some(vm_exit);
    }

    /// Returns a reference to the inner KVM Vm object.
    pub fn kvm_vm(&self) -> &Vm {
        &self.vm
    }

    #[cfg(target_os = "macos")]
    pub fn add_mapping(
        &self,
        reply_sender: Sender<bool>,
        host_addr: u64,
        guest_addr: u64,
        len: u64,
    ) {
        self.vm
            .add_mapping(reply_sender, host_addr, guest_addr, len);
    }

    #[cfg(target_os = "macos")]
    pub fn remove_mapping(&self, reply_sender: Sender<bool>, guest_addr: u64, len: u64) {
        self.vm.remove_mapping(reply_sender, guest_addr, len);
    }
}

/// Constructs a `&[u8]` slice from a host pointer, verifying that the entire
/// slice `[host_ptr, host_ptr + len)` lies within the guest memory region
/// `[region_start, region_start + region_len)`.
///
/// The check uses GPA arithmetic: since `get_host_address` maps GPA→host and the
/// mapping is contiguous within a region, it suffices to verify
/// `addr + len <= region_start + region_len` in GPA space.
///
/// Returns `Err` if:
/// - `host_ptr as usize + len` overflows `usize`, or
/// - `addr + len` overflows `u64`, or
/// - `addr + len > region_start + region_len` (slice extends past region end).
///
/// Prefer [`get_validated_host_ptr`] for new call sites — it bundles the region
/// lookup with the bounds check, making it harder to forget either step.
///
/// # Safety
///
/// The caller must ensure `host_ptr` remains valid for the returned slice's lifetime.
/// This function is only called from [`ValidatedHostPtr::as_slice`], which ties the
/// output lifetime to the `ValidatedHostPtr<'a>` borrow, enforcing the backing
/// `GuestMemoryMmap` outlives the slice.
fn validated_host_slice(
    host_ptr: *const u8,
    len: usize,
    addr: u64,
    region_start: u64,
    region_len: u64,
) -> std::result::Result<&'static [u8], &'static str> {
    // Guard host pointer arithmetic overflow.
    (host_ptr as usize)
        .checked_add(len)
        .ok_or("host pointer arithmetic overflow")?;

    // Guard GPA arithmetic overflow and region bound.
    let region_end = region_start
        .checked_add(region_len)
        .ok_or("region end address overflows u64")?;
    let slice_end = addr
        .checked_add(len as u64)
        .ok_or("guest address + len overflows u64")?;
    if slice_end > region_end {
        return Err("slice extends past end of guest memory region");
    }

    // Safety: We verified no usize overflow above, and the GPA bounds check
    // guarantees the host mapping covers [host_ptr, host_ptr+len) because
    // get_host_address maps a contiguous GPA region to a contiguous host range.
    Ok(unsafe { std::slice::from_raw_parts(host_ptr, len) })
}

/// Mutable variant of [`validated_host_slice`]: constructs a `&mut [u8]` slice from a
/// host pointer, applying the same GPA region bounds check.
///
/// See [`validated_host_slice`] for the invariants, error conditions, and lifetime safety notes.
fn validated_host_slice_mut(
    host_ptr: *mut u8,
    len: usize,
    addr: u64,
    region_start: u64,
    region_len: u64,
) -> std::result::Result<&'static mut [u8], &'static str> {
    // Guard host pointer arithmetic overflow.
    (host_ptr as usize)
        .checked_add(len)
        .ok_or("host pointer arithmetic overflow")?;

    // Guard GPA arithmetic overflow and region bound.
    let region_end = region_start
        .checked_add(region_len)
        .ok_or("region end address overflows u64")?;
    let slice_end = addr
        .checked_add(len as u64)
        .ok_or("guest address + len overflows u64")?;
    if slice_end > region_end {
        return Err("slice extends past end of guest memory region");
    }

    // Safety: same as validated_host_slice, but mutable.
    Ok(unsafe { std::slice::from_raw_parts_mut(host_ptr, len) })
}

/// A host pointer with its backing region bounds pre-validated.
///
/// The lifetime parameter `'a` is tied to the `&'a GuestMemoryMmap` that produced
/// this pointer (via [`get_validated_host_ptr`]), ensuring the pointer cannot outlive
/// the backing memory mapping.
///
/// Can only be constructed by [`get_validated_host_ptr`], which verifies the
/// address is within the region. Use [`as_slice`](ValidatedHostPtr::as_slice) to
/// get a bounded slice — it checks `addr + len <= region_end` before constructing.
///
/// This type exists to make it structurally impossible to call `get_host_address`
/// and then build a raw slice without passing through the region bounds check.
/// GAP-013 class bugs arise when that check is omitted; `ValidatedHostPtr` closes
/// the gap for future call sites.
pub(crate) struct ValidatedHostPtr<'a> {
    ptr: *const u8,
    region_start: u64,
    region_len: u64,
    addr: u64,
    _marker: std::marker::PhantomData<&'a u8>,
}

// SAFETY: The pointer is valid for reads as long as the `GuestMemoryMmap` that
// produced it is alive. The lifetime parameter `'a` enforces this at compile time.
// The underlying GuestMemoryMmap regions are mapped memory that is safe to read
// from multiple threads (the vCPU threads access the same mapping concurrently).
unsafe impl<'a> Send for ValidatedHostPtr<'a> {}

impl<'a> ValidatedHostPtr<'a> {
    /// Returns the raw host pointer. The pointer is valid for `'a` (the lifetime of the
    /// backing `GuestMemoryMmap`). Use [`as_slice`](Self::as_slice) to obtain a
    /// bounds-checked slice from it.
    #[allow(dead_code)] // Used in snapshot paths, not in loom builds
    pub(crate) fn as_ptr(&self) -> *const u8 {
        self.ptr
    }

    /// Constructs a slice of `len` bytes starting at this pointer.
    ///
    /// Returns `Err` if `addr + len > region_start + region_len`.
    pub(crate) fn as_slice(&self, len: usize) -> std::result::Result<&[u8], &'static str> {
        validated_host_slice(self.ptr, len, self.addr, self.region_start, self.region_len)
    }

    /// Constructs a mutable slice of `len` bytes starting at this pointer.
    ///
    /// Returns `Err` if `addr + len > region_start + region_len`.
    pub(crate) fn as_slice_mut(
        &mut self,
        len: usize,
    ) -> std::result::Result<&mut [u8], &'static str> {
        validated_host_slice_mut(
            self.ptr as *mut u8,
            len,
            self.addr,
            self.region_start,
            self.region_len,
        )
    }
}

/// Looks up the host pointer for `addr` in `mem`, returning a [`ValidatedHostPtr`]
/// that carries the region bounds for later slice construction via
/// [`as_slice`](ValidatedHostPtr::as_slice).
///
/// The returned pointer's lifetime is tied to `mem` — it cannot outlive the
/// `GuestMemoryMmap` reference.
///
/// Returns `None` if `addr` does not fall within any memory region.
pub(crate) fn get_validated_host_ptr<'a>(
    mem: &'a GuestMemoryMmap,
    addr: u64,
) -> Option<ValidatedHostPtr<'a>> {
    use vm_memory::{Address, GuestAddress, GuestMemoryBackend, GuestMemoryRegion};
    let guest_addr = GuestAddress(addr);
    let region = mem.find_region(guest_addr)?;
    // GuestMemoryMmap::get_host_address takes a GuestAddress (unlike the region-level
    // method which takes MemoryRegionAddress).
    let ptr = mem.get_host_address(guest_addr).ok()?;
    let region_start = region.start_addr().raw_value();
    let region_len = region.len();
    Some(ValidatedHostPtr {
        ptr: ptr as *const u8,
        region_start,
        region_len,
        addr,
        _marker: std::marker::PhantomData,
    })
}

/// Check which pages in a memory range are resident in memory.
/// Returns a Vec<bool> where true = page is resident, false = non-resident.
/// This is a Linux-only function using the mincore(2) syscall.
#[cfg(target_os = "linux")]
#[cfg(not(feature = "tee"))]
#[allow(dead_code)]
fn mincore_check(host_addr: *const u8, len: usize) -> io::Result<Vec<bool>> {
    let page_count = len.div_ceil(4096);
    let mut vec = vec![0u8; page_count];
    let ret = unsafe { libc::mincore(host_addr as *mut libc::c_void, len, vec.as_mut_ptr()) };
    if ret != 0 {
        return Err(io::Error::last_os_error());
    }
    Ok(vec.iter().map(|&v| v & 1 != 0).collect())
}

impl Subscriber for Vmm {
    /// Handle a read event (EPOLLIN).
    fn process(&mut self, event: &EpollEvent, _: &mut EventManager) {
        let source = event.fd();
        let event_set = event.event_set();

        if source == self.exit_evt.as_raw_fd() && event_set == EventSet::IN {
            debug!("Vmm: exit_evt fired, shutting down");
            let _ = self.exit_evt.read();

            let vcpu_exit_code = self
                .vcpus_handles
                .iter()
                .find_map(|handle| match handle.response_receiver().try_recv() {
                    Ok(VcpuResponse::Exited(exit_code)) => Some(exit_code),
                    _ => None,
                })
                .unwrap_or(FC_EXIT_CODE_OK);

            let vmm_exit_code = self.exit_code.load(Ordering::SeqCst);

            // Log which exit code is being used for shutdown
            if vmm_exit_code != i32::MAX {
                debug!("using vmm exit code: {vmm_exit_code}");
            } else {
                debug!("using vcpu exit code: {vcpu_exit_code}");
            }

            let vm_exit = resolve_vm_exit(vcpu_exit_code, vmm_exit_code);
            self.stop(vm_exit);
        } else {
            error!("Spurious EventManager event for handler: Vmm");
        }
    }

    fn interest_list(&self) -> Vec<EpollEvent> {
        vec![EpollEvent::new(
            EventSet::IN,
            self.exit_evt.as_raw_fd() as u64,
        )]
    }
}

/// Helper function to resolve VmExit variant from exit codes.
/// This is the core logic used by Subscriber::process() to determine
/// the correct VmExit variant based on vCPU exit code and VMM exit code.
/// Tests call this same function to verify the dispatch logic.
pub(crate) fn resolve_vm_exit(vcpu_exit_code: u8, vmm_exit_code: i32) -> crate::vm_exit::VmExit {
    if vcpu_exit_code == FC_EXIT_CODE_REBOOT {
        crate::vm_exit::VmExit::RebootRequested
    } else if vcpu_exit_code == FC_EXIT_CODE_GENERIC_ERROR {
        crate::vm_exit::VmExit::Error {
            message: "vCPU fatal error".into(),
        }
    } else {
        let exit_code = if vmm_exit_code != i32::MAX {
            vmm_exit_code
        } else {
            vcpu_exit_code as i32
        };
        crate::vm_exit::VmExit::Shutdown { exit_code }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Helper function to check if dirty tracking is enabled.
    /// This is used in both create_incremental_snapshot implementations.
    fn check_dirty_tracking_enabled(
        dirty_tracking_enabled: bool,
    ) -> std::result::Result<(), snapshot::SnapshotError> {
        if !dirty_tracking_enabled {
            return Err(snapshot::SnapshotError::DirtyTrackingNotEnabled);
        }
        Ok(())
    }

    /// AC1.9: create_incremental_snapshot requires dirty_tracking_enabled
    #[test]
    fn test_incremental_snapshot_requires_dirty_tracking() {
        // Guard check before dirty_tracking was enabled
        let result = check_dirty_tracking_enabled(false);
        assert!(matches!(
            result,
            Err(snapshot::SnapshotError::DirtyTrackingNotEnabled)
        ));

        // Guard check after dirty_tracking is enabled
        let result = check_dirty_tracking_enabled(true);
        assert!(result.is_ok());
    }

    /// Test VM exit enum variants and derives
    #[test]
    fn test_vm_exit_enum() {
        // Test Shutdown variant construction and clone
        let exit_shutdown = crate::vm_exit::VmExit::Shutdown { exit_code: 0 };
        let exit_shutdown_cloned = exit_shutdown.clone();
        assert_eq!(exit_shutdown, exit_shutdown_cloned);

        // Test different exit codes
        let exit_42 = crate::vm_exit::VmExit::Shutdown { exit_code: 42 };
        assert_ne!(exit_shutdown, exit_42);

        // Test RebootRequested variant
        let exit_reboot = crate::vm_exit::VmExit::RebootRequested;
        let exit_reboot_cloned = exit_reboot.clone();
        assert_eq!(exit_reboot, exit_reboot_cloned);

        // Test Error variant
        let exit_error = crate::vm_exit::VmExit::Error {
            message: "test error".into(),
        };
        let exit_error_cloned = exit_error.clone();
        assert_eq!(exit_error, exit_error_cloned);

        // Test Debug trait
        let debug_str = format!("{:?}", exit_shutdown);
        assert!(debug_str.contains("Shutdown"));
    }

    /// Test vm-exit.AC1.1: Normal guest shutdown (HLT) returns Shutdown { exit_code: 0 }
    #[test]
    fn test_shutdown_with_zero_exit_code() {
        let vm_exit = resolve_vm_exit(FC_EXIT_CODE_OK, i32::MAX);
        assert_eq!(vm_exit, crate::vm_exit::VmExit::Shutdown { exit_code: 0 });
    }

    /// Test vm-exit.AC1.2: Guest-set exit code is returned in Shutdown variant
    #[test]
    fn test_shutdown_with_guest_exit_code() {
        // Guest set exit code via vmm_exit_code (virtio-fs ioctl)
        let vm_exit = resolve_vm_exit(FC_EXIT_CODE_OK, 42);
        assert_eq!(vm_exit, crate::vm_exit::VmExit::Shutdown { exit_code: 42 });
    }

    /// Test vm-exit.AC1.3: KVM_SYSTEM_EVENT_RESET returns RebootRequested
    #[test]
    fn test_reboot_requested() {
        let vm_exit = resolve_vm_exit(FC_EXIT_CODE_REBOOT, i32::MAX);
        assert_eq!(vm_exit, crate::vm_exit::VmExit::RebootRequested);
    }

    /// Test vm-exit.AC2.1: vCPU fatal errors return Error variant
    #[test]
    fn test_vcpu_fatal_error() {
        let vm_exit = resolve_vm_exit(FC_EXIT_CODE_GENERIC_ERROR, i32::MAX);
        match vm_exit {
            crate::vm_exit::VmExit::Error { ref message } => {
                assert_eq!(message, "vCPU fatal error");
            }
            _ => panic!("Expected Error variant"),
        }
    }

    /// Test shared exit state storage contract
    #[test]
    fn test_shared_vm_exit_storage() {
        let vm_exit: crate::vm_exit::SharedVmExit = Arc::new(Mutex::new(None));

        // Initially should be None
        {
            let guard = vm_exit.lock().expect("Poisoned lock");
            assert!(guard.is_none());
        }

        // Store a VmExit value
        {
            let mut guard = vm_exit.lock().expect("Poisoned lock");
            *guard = Some(crate::vm_exit::VmExit::Shutdown { exit_code: 0 });
        }

        // Verify it was stored
        {
            let guard = vm_exit.lock().expect("Poisoned lock");
            assert_eq!(
                *guard,
                Some(crate::vm_exit::VmExit::Shutdown { exit_code: 0 })
            );
        }
    }

    /// Test mem-balloon.AC2.3: Full snapshot excludes all inflated pages
    /// Test AC2.6: Verify apply_reclaimed_pages zeros guest memory.
    /// This is a minimal test that apply_reclaimed_pages correctly writes zeros
    /// to the specified guest addresses.
    #[test]
    #[cfg(feature = "snapshot")]
    fn test_apply_reclaimed_pages_zeros_memory() {
        use vm_memory::{Bytes, GuestAddress, GuestMemoryMmap};

        // Create a small guest memory region
        let mem = GuestMemoryMmap::from_ranges(&[(GuestAddress(0), 16384)])
            .expect("Failed to create guest memory");

        // Write some non-zero data to a page
        let page_addr = GuestAddress(4096);
        let test_data = vec![0xDEu8; 4096];
        mem.write_slice(&test_data, page_addr)
            .expect("Failed to write test data");

        // Verify data was written
        let mut verify = vec![0u8; 4096];
        mem.read_slice(&mut verify, page_addr)
            .expect("Failed to read test data");
        assert_eq!(verify[0], 0xDE);

        // Now apply_reclaimed_pages to zero that page
        snapshot::apply_reclaimed_pages(&mem, &[4096u64]).expect("apply_reclaimed_pages failed");

        // Verify the page is now zeros
        mem.read_slice(&mut verify, page_addr)
            .expect("Failed to read after reclaim");
        assert!(
            verify.iter().all(|&b| b == 0),
            "Page should be all zeros after reclaim"
        );
    }

    /// Test sparse file offset calculation.
    /// Verifies that the offset calculation for guest addresses works correctly
    /// with multiple RAM regions.
    #[test]
    #[cfg(feature = "snapshot")]
    fn test_sparse_file_offset_calculation() {
        // Simulate RAM regions: (guest_addr, size)
        let ram_regions = vec![(0u64, 4096u64), (4096u64, 4096u64), (8192u64, 4096u64)];

        // Test offset calculation for various guest addresses
        let test_cases = vec![
            // (guest_addr, expected_offset)
            (0u64, 0u64),       // First region, start
            (4096u64, 4096u64), // Second region, start
            (8192u64, 8192u64), // Third region, start
        ];

        for (guest_addr, expected_offset) in test_cases {
            let mut offset = 0u64;
            let mut found = false;
            for (region_addr, region_size) in &ram_regions {
                if *region_addr <= guest_addr && guest_addr < region_addr + region_size {
                    offset += guest_addr - region_addr;
                    found = true;
                    break;
                }
                offset += region_size;
            }
            assert!(
                found,
                "Address 0x{:x} should be in one of the regions",
                guest_addr
            );
            assert_eq!(
                offset, expected_offset,
                "Offset mismatch for address 0x{:x}",
                guest_addr
            );
        }
    }

    /// AC2.4 Unit: `test_mincore_check_after_madvise`
    /// Verify that mincore_check detects non-resident pages after madvise(MADV_DONTNEED).
    #[test]
    #[cfg(target_os = "linux")]
    fn test_mincore_check_after_madvise() {
        // Allocate anonymous memory
        let size = 8192; // 2 pages
        let host_addr = unsafe {
            libc::mmap(
                std::ptr::null_mut(),
                size,
                libc::PROT_READ | libc::PROT_WRITE,
                libc::MAP_PRIVATE | libc::MAP_ANONYMOUS,
                -1,
                0,
            )
        };

        assert_ne!(
            host_addr,
            libc::MAP_FAILED as *mut libc::c_void,
            "mmap should succeed"
        );

        let host_addr = host_addr as *const u8;

        // Touch the page to make it resident
        unsafe {
            std::ptr::write(host_addr as *mut u8, 0xFF);
        }

        // Call madvise(MADV_DONTNEED) to discard the page
        let ret =
            unsafe { libc::madvise(host_addr as *mut libc::c_void, 4096, libc::MADV_DONTNEED) };
        assert_eq!(ret, 0, "madvise should succeed");

        // Check residency using mincore_check
        let residency = mincore_check(host_addr, 4096).expect("mincore_check should succeed");
        assert_eq!(residency.len(), 1, "Should have 1 page result");
        assert_eq!(
            residency[0], false,
            "Page should be non-resident after MADV_DONTNEED (bit 0 should be clear)"
        );

        // Clean up
        unsafe {
            libc::munmap(host_addr as *mut libc::c_void, size);
        }
    }

    /// AC2.7 Unit: `test_mincore_reused_page_not_excluded`
    /// Verify that mincore_check detects resident pages after they are reused (written to after MADV_DONTNEED).
    #[test]
    #[cfg(target_os = "linux")]
    fn test_mincore_reused_page_not_excluded() {
        // Allocate anonymous memory
        let size = 8192; // 2 pages
        let host_addr = unsafe {
            libc::mmap(
                std::ptr::null_mut(),
                size,
                libc::PROT_READ | libc::PROT_WRITE,
                libc::MAP_PRIVATE | libc::MAP_ANONYMOUS,
                -1,
                0,
            )
        };

        assert_ne!(
            host_addr,
            libc::MAP_FAILED as *mut libc::c_void,
            "mmap should succeed"
        );

        let host_addr = host_addr as *const u8;

        // Call madvise(MADV_DONTNEED) to discard the page
        let ret =
            unsafe { libc::madvise(host_addr as *mut libc::c_void, 4096, libc::MADV_DONTNEED) };
        assert_eq!(ret, 0, "madvise should succeed");

        // Write non-zero data to the page (making it resident again)
        unsafe {
            std::ptr::write(host_addr as *mut u8, 0xAA);
        }

        // Check residency using mincore_check
        let residency = mincore_check(host_addr, 4096).expect("mincore_check should succeed");
        assert_eq!(residency.len(), 1, "Should have 1 page result");
        assert_eq!(
            residency[0], true,
            "Page should be resident after write (bit 0 should be set)"
        );

        // Clean up
        unsafe {
            libc::munmap(host_addr as *mut libc::c_void, size);
        }
    }

    /// AC2.9 Unit: `test_snapshot_no_balloon_no_regression`
    /// Verify that VmSnapshot with no excluded pages round-trips correctly through serialization.
    #[test]
    #[cfg(feature = "snapshot")]
    fn test_snapshot_no_balloon_no_regression() {
        use crate::snapshot::{SnapshotHeader, VmSnapshot, SNAPSHOT_MAGIC, SNAPSHOT_VERSION};

        // Create a VmSnapshot with empty excluded_pages (no balloon scenario)
        let header = SnapshotHeader {
            magic: SNAPSHOT_MAGIC,
            version: SNAPSHOT_VERSION,
            vcpu_count: 2,
            ram_regions: vec![(0x0, 0x100000)],
            nested_enabled: false,
        };

        let original = VmSnapshot {
            header: header.clone(),
            vcpu_states: vec![vec![0x01], vec![0x02]],
            device_states: vec![],
            gic_state: None,
            vm_state: None,
            excluded_pages: Vec::new(), // No balloon-reclaimed pages
        };

        // Serialize
        let serialized = bincode_next::encode_to_vec(&original, bincode_next::config::standard()).expect("serialization should succeed");

        // Deserialize
        let deserialized: VmSnapshot =
            bincode_next::decode_from_slice(&serialized, bincode_next::config::standard().with_limit::<{ snapshot::VMSTATE_MAX_SIZE as usize }>())
                .map(|(val, _)| val)
                .expect("deserialization should succeed");

        // Verify the excluded_pages field round-tripped correctly
        assert_eq!(
            deserialized.excluded_pages.len(),
            0,
            "excluded_pages should be empty after round-trip"
        );
        assert_eq!(
            deserialized.header.magic, SNAPSHOT_MAGIC,
            "header.magic should match"
        );
        assert_eq!(
            deserialized.vcpu_states.len(),
            2,
            "vCPU states should be preserved"
        );
    }

    /// AC3.1 Unit: `test_incremental_snapshot_empty_reclaimed`
    /// Verify that IncrementalSnapshot with empty reclaimed_pages round-trips correctly.
    #[test]
    #[cfg(feature = "snapshot")]
    fn test_incremental_snapshot_empty_reclaimed() {
        use crate::snapshot::{
            IncrementalSnapshot, SnapshotHeader, SNAPSHOT_MAGIC, SNAPSHOT_VERSION,
        };

        let header = SnapshotHeader {
            magic: SNAPSHOT_MAGIC,
            version: SNAPSHOT_VERSION,
            vcpu_count: 1,
            ram_regions: vec![(0x0, 0x100000)],
            nested_enabled: false,
        };

        let original = IncrementalSnapshot {
            header: header.clone(),
            vcpu_states: vec![vec![0xFF]],
            device_states: vec![],
            dirty_pages: vec![],
            gic_state: None,
            vm_state: None,
            reclaimed_pages: Vec::new(), // No reclaimed pages
        };

        // Serialize
        let serialized = bincode_next::encode_to_vec(&original, bincode_next::config::standard()).expect("serialization should succeed");

        // Deserialize
        let deserialized: IncrementalSnapshot =
            bincode_next::decode_from_slice(&serialized, bincode_next::config::standard().with_limit::<{ snapshot::VMSTATE_MAX_SIZE as usize }>())
                .map(|(val, _)| val)
                .expect("deserialization should succeed");

        // Verify the reclaimed_pages field round-tripped correctly
        assert_eq!(
            deserialized.reclaimed_pages.len(),
            0,
            "reclaimed_pages should be empty after round-trip"
        );
        assert_eq!(
            deserialized.header.magic, SNAPSHOT_MAGIC,
            "header.magic should match"
        );
    }
}

/// GAP-013 (GREEN): dirty page slice bounds — `validated_host_slice` enforces region check.
///
/// All call sites that previously used:
///   `let host_addr = get_host_address(addr)?;`
///   `unsafe { slice::from_raw_parts(host_addr, page_size) }`
/// without asserting `addr + page_size <= region_end` have been replaced with
/// `validated_host_slice(host_ptr, len, addr, region_start, region_len)` which
/// returns `Err` when the slice would extend past the region.
///
/// These proofs are GREEN-phase: they verify that `validated_host_slice` correctly
/// enforces the region bound for all symbolic inputs.
#[cfg(kani)]
mod verification {
    /// GAP-013 Proof 1 (GREEN): `validated_host_slice` enforces region bounds.
    ///
    /// When `validated_host_slice` returns `Ok`, the entire slice
    /// `[addr, addr + len)` is guaranteed to lie within
    /// `[region_start, region_start + region_len)`.
    ///
    /// This replaces the RED-phase proof that modelled the old bare
    /// `slice::from_raw_parts` pattern (which could produce out-of-bounds slices).
    ///
    /// Expected result: PASS.
    /// Bound: no loops; no unwind attribute needed.
    #[kani::proof]
    fn proof_collect_dirty_pages_slice_in_bounds() {
        // Symbolic region descriptor (equivalent to a KVM mem_slot entry).
        let region_start: u64 = kani::any();
        let region_len: u64 = kani::any();
        let page_size: u64 = 4096;

        // Preconditions that hold in the production path:
        // - region_len is a multiple of page_size (KVM requires page-aligned regions)
        // - region_len is at least one page
        // - region_start + region_len does not overflow (valid GPA range)
        kani::assume(region_len > 0);
        kani::assume(region_len % page_size == 0);
        kani::assume(region_start.checked_add(region_len).is_some());

        // Symbolic dirty page index within the region.
        let page_idx: u64 = kani::any();
        kani::assume(page_idx.checked_mul(page_size).is_some());
        let page_offset = page_idx * page_size;
        kani::assume(region_start.checked_add(page_offset).is_some());
        let addr = region_start + page_offset;
        let region_end = region_start + region_len;
        // Precondition from production code: get_host_address validates addr < region_end.
        kani::assume(addr < region_end);

        // Model host_ptr as a symbolic but valid-looking non-null pointer.
        // We only verify arithmetic; Kani cannot dereference unbacked symbolics,
        // so we pass a concrete stack buffer's pointer offset by a symbolic amount.
        let buf: [u8; 4096] = kani::any();
        let host_ptr: *const u8 = buf.as_ptr();

        // Call validated_host_slice with the same symbolic inputs.
        let result = super::validated_host_slice(
            host_ptr,
            page_size as usize,
            addr,
            region_start,
            region_len,
        );

        // When validated_host_slice succeeds, addr + page_size <= region_end must hold.
        // This is the core safety invariant of GAP-013.
        if result.is_ok() {
            kani::assert(
                addr.checked_add(page_size)
                    .map(|end| end <= region_end)
                    .unwrap_or(false),
                "GAP-013: validated_host_slice Ok implies addr + len <= region_end",
            );
        }

        // Conversely: if addr + page_size > region_end, validated_host_slice must Err.
        if addr
            .checked_add(page_size)
            .map_or(true, |end| end > region_end)
        {
            kani::assert(
                result.is_err(),
                "GAP-013: validated_host_slice must Err when slice exceeds region",
            );
        }
    }
}
