// Copyright 2018 Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0
//
// Portions Copyright 2017 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the THIRD-PARTY file.

//! Virtual Machine Monitor that leverages the Linux Kernel-based Virtual Machine (KVM),
//! and other virtualization features to run a single lightweight micro-virtual
//! machine (microVM).
//#![deny(missing_docs)]

#[macro_use]
extern crate log;

/// Handles setup and initialization a `Vmm` object.
pub mod builder;
pub(crate) mod device_manager;
/// VM exit reasons and shared exit state.
pub mod vm_exit;
/// Dirty page bitmap for incremental snapshots.
#[cfg(target_os = "macos")]
pub mod dirty_bitmap;
/// Resource store for configured microVM resources.
pub mod resources;
/// Signal handling utilities.
#[cfg(target_os = "linux")]
pub mod signal_handler;
/// VM snapshot and restore support.
pub mod snapshot;
/// Wrappers over structures used to configure the VMM.
pub mod vmm_config;

#[cfg(target_os = "linux")]
mod linux;
#[cfg(target_os = "linux")]
use crate::linux::vstate;
#[cfg(target_os = "macos")]
mod macos;
mod terminal;
pub mod worker;

#[cfg(target_os = "macos")]
use macos::vstate;

use std::fmt::{Display, Formatter};
use std::io;
use std::os::unix::io::AsRawFd;
use std::sync::atomic::{AtomicBool, AtomicI32, Ordering};
use std::sync::{Arc, Mutex};
use std::time::Duration;

#[cfg(target_arch = "x86_64")]
use crate::device_manager::legacy::PortIODeviceManager;
use crate::device_manager::mmio::MMIODeviceManager;
use crate::vstate::VcpuEvent;
use crate::vstate::{Vcpu, VcpuHandle, VcpuResponse, Vm};

use arch::{ArchMemoryInfo, InitrdConfig};
#[cfg(target_os = "macos")]
use crossbeam_channel::Sender;
#[cfg(any(target_arch = "aarch64", target_arch = "riscv64"))]
use devices::fdt;
use devices::legacy::IrqChip;
use devices::virtio::VmmExitObserver;
use devices::{BusDevice, DeviceType};
use kernel::cmdline::Cmdline as KernelCmdline;
use polly::event_manager::{self, EventManager, Subscriber};
use utils::epoll::{EpollEvent, EventSet};
use utils::eventfd::EventFd;
#[cfg(target_os = "macos")]
use vm_memory::Address;
use vm_memory::GuestMemoryMmap;

/// Success exit code.
pub const FC_EXIT_CODE_OK: u8 = 0;
/// Generic error exit code.
pub const FC_EXIT_CODE_GENERIC_ERROR: u8 = 1;
/// Generic exit code for an error considered not possible to occur if the program logic is sound.
pub const FC_EXIT_CODE_UNEXPECTED_ERROR: u8 = 2;
/// Guest requested a reboot (KVM_SYSTEM_EVENT_RESET).
pub const FC_EXIT_CODE_REBOOT: u8 = 3;
/// Firecracker was shut down after intercepting a restricted system call.
pub const FC_EXIT_CODE_BAD_SYSCALL: u8 = 148;
/// Firecracker was shut down after intercepting `SIGBUS`.
pub const FC_EXIT_CODE_SIGBUS: u8 = 149;
/// Firecracker was shut down after intercepting `SIGSEGV`.
pub const FC_EXIT_CODE_SIGSEGV: u8 = 150;
/// Bad configuration for microvm's resources, when using a single json.
pub const FC_EXIT_CODE_BAD_CONFIGURATION: u8 = 152;
/// Command line arguments parsing error.
pub const FC_EXIT_CODE_ARG_PARSING: u8 = 153;

/// Errors associated with the VMM internal logic. These errors cannot be generated by direct user
/// input, but can result from bad configuration of the host (for example if Firecracker doesn't
/// have permissions to open the KVM fd).
#[derive(Debug)]
pub enum Error {
    /// This error is thrown by the minimal boot loader implementation.
    ConfigureSystem(arch::Error),
    /// Legacy devices work with Event file descriptors and the creation can fail because
    /// of resource exhaustion.
    #[cfg(target_arch = "x86_64")]
    CreateLegacyDevice(device_manager::legacy::Error),
    /// Cannot read from an Event file descriptor.
    EventFd(io::Error),
    /// Polly error wrapper.
    EventManager(event_manager::Error),
    /// I8042 Error.
    I8042Error(devices::legacy::I8042DeviceError),
    /// Cannot access kernel file.
    KernelFile(io::Error),
    /// Cannot open /dev/kvm. Either the host does not have KVM or Firecracker does not have
    /// permission to open the file descriptor.
    KvmContext(vstate::Error),
    #[cfg(target_arch = "x86_64")]
    /// Cannot add devices to the Legacy I/O Bus.
    LegacyIOBus(device_manager::legacy::Error),
    /// Cannot load command line.
    LoadCommandline(kernel::cmdline::Error),
    /// Cannot add a device to the MMIO Bus.
    RegisterMMIODevice(device_manager::mmio::Error),
    /// Write to the serial console failed.
    Serial(io::Error),
    #[cfg(any(target_arch = "aarch64", target_arch = "riscv64"))]
    /// Cannot generate or write FDT
    SetupFDT(devices::fdt::Error),
    /// Cannot create Timer file descriptor.
    TimerFd(io::Error),
    /// Vcpu error.
    Vcpu(vstate::Error),
    /// Cannot send event to vCPU.
    VcpuEvent(vstate::Error),
    /// Cannot create a vCPU handle.
    VcpuHandle(vstate::Error),
    /// vCPU pause failed.
    VcpuPause,
    /// vCPU resume failed.
    VcpuResume,
    /// Cannot spawn a new Vcpu thread.
    VcpuSpawn(std::io::Error),
    /// Vm error.
    Vm(vstate::Error),
    /// Error thrown by observer object on Vmm initialization.
    VmmObserverInit(utils::errno::Error),
    /// Error thrown by observer object on Vmm teardown.
    VmmObserverTeardown(utils::errno::Error),
}

impl Display for Error {
    fn fmt(&self, f: &mut Formatter) -> std::fmt::Result {
        use self::Error::*;

        match self {
            ConfigureSystem(e) => write!(f, "System configuration error: {e:?}"),
            #[cfg(target_arch = "x86_64")]
            CreateLegacyDevice(e) => write!(f, "Error creating legacy device: {e:?}"),
            EventFd(e) => write!(f, "Event fd error: {e}"),
            EventManager(e) => write!(f, "Event manager error: {e:?}"),
            I8042Error(e) => write!(f, "I8042 error: {e}"),
            KernelFile(e) => write!(f, "Cannot access kernel file: {e}"),
            KvmContext(e) => write!(f, "Failed to validate KVM support: {e:?}"),
            #[cfg(target_arch = "x86_64")]
            LegacyIOBus(e) => write!(f, "Cannot add devices to the legacy I/O Bus. {e}"),
            LoadCommandline(e) => write!(f, "Cannot load command line: {e}"),
            RegisterMMIODevice(e) => write!(f, "Cannot add a device to the MMIO Bus. {e}"),
            Serial(e) => write!(f, "Error writing to the serial console: {e:?}"),
            #[cfg(any(target_arch = "aarch64", target_arch = "riscv64"))]
            SetupFDT(e) => write!(f, "Error generating or writing FDT: {e:?}"),
            TimerFd(e) => write!(f, "Error creating timer fd: {e}"),
            Vcpu(e) => write!(f, "Vcpu error: {e}"),
            VcpuEvent(e) => write!(f, "Cannot send event to vCPU. {e:?}"),
            VcpuHandle(e) => write!(f, "Cannot create a vCPU handle. {e}"),
            VcpuPause => write!(f, "vCPUs pause failed."),
            VcpuResume => write!(f, "vCPUs resume failed."),
            VcpuSpawn(e) => write!(f, "Cannot spawn Vcpu thread: {e}"),
            Vm(e) => write!(f, "Vm error: {e}"),
            VmmObserverInit(e) => write!(
                f,
                "Error thrown by observer object on Vmm initialization: {e}"
            ),
            VmmObserverTeardown(e) => {
                write!(f, "Error thrown by observer object on Vmm teardown: {e}")
            }
        }
    }
}

/// Trait for objects that need custom initialization and teardown during the Vmm lifetime.
pub trait VmmEventsObserver {
    /// This function will be called during microVm boot.
    fn on_vmm_boot(&mut self) -> std::result::Result<(), utils::errno::Error> {
        Ok(())
    }
    /// This function will be called on microVm teardown.
    fn on_vmm_stop(&mut self) -> std::result::Result<(), utils::errno::Error> {
        Ok(())
    }
}

/// Shorthand result type for internal VMM commands.
pub type Result<T> = std::result::Result<T, Error>;

/// Contains the state and associated methods required for the Firecracker VMM.
pub struct Vmm {
    // Guest VM core resources.
    guest_memory: GuestMemoryMmap,
    arch_memory_info: ArchMemoryInfo,

    kernel_cmdline: KernelCmdline,

    vcpus_handles: Vec<VcpuHandle>,
    exit_evt: EventFd,
    vm: Vm,
    exit_observers: Vec<Arc<Mutex<dyn VmmExitObserver>>>,
    exit_code: Arc<AtomicI32>,
    vm_exit: crate::vm_exit::SharedVmExit,
    vcpu_exit_flag: Arc<AtomicBool>,

    // Guest VM devices.
    mmio_device_manager: MMIODeviceManager,
    #[cfg(target_arch = "x86_64")]
    pio_device_manager: PortIODeviceManager,
    #[cfg(target_os = "macos")]
    dirty_bitmaps: Vec<dirty_bitmap::DirtyBitmap>,

    // Snapshot and dirty tracking state.
    #[cfg_attr(not(feature = "snapshot"), allow(dead_code))]
    nested_enabled: bool,
    #[cfg_attr(not(feature = "snapshot"), allow(dead_code))]
    dirty_tracking_enabled: bool,

    // Interrupt controller state needed for snapshots.
    #[cfg(target_os = "macos")]
    #[cfg_attr(not(feature = "snapshot"), allow(dead_code))]
    vcpu_list: Arc<devices::legacy::VcpuList>,
    #[cfg(target_os = "macos")]
    #[cfg_attr(not(feature = "snapshot"), allow(dead_code))]
    intc: IrqChip,
    #[cfg(all(target_os = "linux", target_arch = "aarch64", feature = "snapshot"))]
    intc: IrqChip,
}

impl Vmm {
    /// Gets the the specified bus device.
    pub fn get_bus_device(
        &self,
        device_type: DeviceType,
        device_id: &str,
    ) -> Option<&Mutex<dyn BusDevice>> {
        self.mmio_device_manager.get_device(device_type, device_id)
    }

    /// Starts the microVM vcpus.
    pub fn start_vcpus(&mut self, mut vcpus: Vec<Vcpu>) -> Result<()> {
        self.start_vcpus_paused(&mut vcpus)?;

        // The vcpus start off in the `Paused` state, let them run.
        self.resume_vcpus()?;

        Ok(())
    }

    /// Starts the microVM vcpus without resuming them.
    ///
    /// After this call vCPU threads exist but are sitting in their initial
    /// event loop waiting for Resume or RestoreState. Use this for cold
    /// restore from snapshot.
    pub fn start_vcpus_paused(&mut self, vcpus: &mut Vec<Vcpu>) -> Result<()> {
        Vcpu::register_kick_signal_handler();

        self.vcpus_handles.reserve(vcpus.len());

        for vcpu in vcpus.drain(..) {
            let mut vcpu = vcpu;
            vcpu.set_mmio_bus(self.mmio_device_manager.bus.clone());

            self.vcpus_handles
                .push(vcpu.start_threaded().map_err(Error::VcpuHandle)?);
        }

        Ok(())
    }

    /// Sends a pause command to all vcpus and waits for confirmation.
    pub fn pause_vcpus(&mut self) -> Result<()> {
        for handle in self.vcpus_handles.iter() {
            handle
                .send_event(VcpuEvent::Pause)
                .map_err(Error::VcpuEvent)?;
        }
        for handle in self.vcpus_handles.iter() {
            match handle
                .response_receiver()
                .recv_timeout(Duration::from_millis(1000))
            {
                Ok(VcpuResponse::Paused) => (),
                _ => return Err(Error::VcpuPause),
            }
        }
        Ok(())
    }

    /// Save all vCPU states. vCPUs must already be paused.
    #[cfg(target_os = "macos")]
    pub fn save_vcpu_states(&self) -> Result<Vec<hvf::Aarch64VcpuState>> {
        let mut states = Vec::with_capacity(self.vcpus_handles.len());
        for handle in self.vcpus_handles.iter() {
            states.push(handle.save_state().map_err(Error::Vcpu)?);
        }
        Ok(states)
    }

    /// Restore all vCPU states. vCPUs must already be paused.
    #[cfg(target_os = "macos")]
    pub fn restore_vcpu_states(&self, states: Vec<hvf::Aarch64VcpuState>) -> Result<()> {
        if states.len() != self.vcpus_handles.len() {
            return Err(Error::VcpuPause);
        }
        // Read host counter once so all vCPUs get the same reference point
        // (avoids inter-vCPU skew from restore loop timing).
        let host_now = hvf::host_counter_now();
        for (handle, mut state) in self.vcpus_handles.iter().zip(states.into_iter()) {
            state.host_counter_at_restore = Some(host_now);
            handle.restore_state(state).map_err(Error::Vcpu)?;
        }
        Ok(())
    }

    /// Save interrupt controller state (pending IRQs + GIC registers) for snapshot.
    #[cfg(all(target_os = "macos", feature = "snapshot"))]
    fn save_interrupt_controller_state(
        &self,
    ) -> std::result::Result<Option<Vec<u8>>, snapshot::SnapshotError> {
        let pending_irqs = self.vcpu_list.save_interrupt_state();
        let gic_registers = self.intc.lock().unwrap().save_snapshot_state();

        let ic_snapshot = snapshot::InterruptControllerSnapshot {
            pending_irqs,
            gic_registers,
        };

        let data = bincode::serialize(&ic_snapshot)
            .map_err(|e| snapshot::SnapshotError::Serialize(e.to_string()))?;
        Ok(Some(data))
    }

    /// Restore interrupt controller state (pending IRQs + GIC registers) from snapshot.
    #[cfg(all(target_os = "macos", feature = "snapshot"))]
    fn restore_interrupt_controller_state(
        &self,
        data: &[u8],
    ) -> std::result::Result<(), snapshot::SnapshotError> {
        let ic_snapshot: snapshot::InterruptControllerSnapshot = bincode::deserialize(data)
            .map_err(|e| snapshot::SnapshotError::Deserialize(e.to_string()))?;

        self.vcpu_list
            .restore_interrupt_state(&ic_snapshot.pending_irqs);

        if let Some(gic_data) = &ic_snapshot.gic_registers {
            self.intc.lock().unwrap().restore_snapshot_state(gic_data);
        }

        Ok(())
    }

    /// Save all vCPU states as opaque bytes. vCPUs must already be paused.
    #[cfg(all(target_os = "linux", feature = "snapshot"))]
    pub fn save_vcpu_states(&self) -> Result<Vec<Vec<u8>>> {
        let mut states = Vec::with_capacity(self.vcpus_handles.len());
        for handle in self.vcpus_handles.iter() {
            states.push(handle.save_state().map_err(Error::Vcpu)?);
        }
        Ok(states)
    }

    /// Restore all vCPU states from opaque bytes. vCPUs must already be paused.
    #[cfg(all(target_os = "linux", feature = "snapshot"))]
    pub fn restore_vcpu_states(&self, states: Vec<Vec<u8>>) -> Result<()> {
        if states.len() != self.vcpus_handles.len() {
            return Err(Error::VcpuPause);
        }
        for (handle, state) in self.vcpus_handles.iter().zip(states.into_iter()) {
            handle.restore_state(state).map_err(Error::Vcpu)?;
        }
        Ok(())
    }

    /// Save interrupt controller state for snapshot (Linux/aarch64).
    #[cfg(all(target_os = "linux", target_arch = "aarch64", feature = "snapshot"))]
    fn save_interrupt_controller_state(
        &self,
    ) -> std::result::Result<Option<Vec<u8>>, snapshot::SnapshotError> {
        let gic_data = self.intc.lock().unwrap().save_snapshot_state();
        Ok(gic_data)
    }

    /// Restore interrupt controller state from snapshot (Linux/aarch64).
    #[cfg(all(target_os = "linux", target_arch = "aarch64", feature = "snapshot"))]
    fn restore_interrupt_controller_state(
        &self,
        data: &[u8],
    ) -> std::result::Result<(), snapshot::SnapshotError> {
        self.intc.lock().unwrap().restore_snapshot_state(data);
        Ok(())
    }

    /// Create a full snapshot of the VM. vCPUs must already be paused.
    #[cfg(all(target_os = "linux", feature = "snapshot"))]
    pub fn create_snapshot(
        &mut self,
        path: &std::path::Path,
    ) -> std::result::Result<(), snapshot::SnapshotError> {
        let device_states = self
            .mmio_device_manager
            .save_all_device_states()
            .map_err(|e| {
                snapshot::SnapshotError::Serialize(format!("Failed to save device states: {e}"))
            })?;

        let vcpu_states = self.save_vcpu_states().map_err(|e| {
            snapshot::SnapshotError::Serialize(format!("Failed to save vCPU states: {e}"))
        })?;

        #[cfg(target_arch = "aarch64")]
        let gic_state = self.save_interrupt_controller_state()?;
        #[cfg(not(target_arch = "aarch64"))]
        let gic_state = None;

        #[cfg(target_arch = "x86_64")]
        let vm_state = Some(
            bincode::serialize(&self.vm.save_state().map_err(|e| {
                snapshot::SnapshotError::Serialize(format!("Failed to save VM state: {e}"))
            })?)
            .map_err(|e| snapshot::SnapshotError::Serialize(e.to_string()))?,
        );
        #[cfg(not(target_arch = "x86_64"))]
        let vm_state = None;

        snapshot::create_full_snapshot(
            path,
            &self.guest_memory,
            vcpu_states,
            device_states,
            gic_state,
            vm_state,
            false,
        )
    }

    /// Restore a full snapshot into the running VM. vCPUs must already be paused.
    #[cfg(all(target_os = "linux", feature = "snapshot"))]
    pub fn restore_snapshot(
        &mut self,
        path: &std::path::Path,
    ) -> std::result::Result<(), snapshot::SnapshotError> {
        let vmstate = snapshot::load_vmstate(&path.join("vmstate"))?;
        snapshot::validate_header_for_vm(
            &vmstate.header,
            &self.guest_memory,
            self.vcpus_handles.len(),
            self.nested_enabled,
        )?;

        self.mmio_device_manager
            .quiesce_all_device_workers(snapshot::SNAPSHOT_QUIESCE_TIMEOUT)
            .map_err(|e| {
                snapshot::SnapshotError::Deserialize(format!(
                    "Failed to quiesce device workers before restore: {e}"
                ))
            })?;

        snapshot::load_memory(&self.guest_memory, &path.join("memory"))?;

        #[cfg(target_arch = "aarch64")]
        if let Some(gic_data) = &vmstate.gic_state {
            self.restore_interrupt_controller_state(gic_data)?;
        }

        #[cfg(target_arch = "x86_64")]
        if let Some(data) = &vmstate.vm_state {
            let state: vstate::VmState = bincode::deserialize(data)
                .map_err(|e| snapshot::SnapshotError::Deserialize(e.to_string()))?;
            self.vm.restore_state(&state).map_err(|e| {
                snapshot::SnapshotError::Deserialize(format!("Failed to restore VM state: {e}"))
            })?;
        }

        self.mmio_device_manager
            .restore_all_device_states(&vmstate.device_states)
            .map_err(|e| {
                snapshot::SnapshotError::Deserialize(format!(
                    "Failed to restore device states: {e}"
                ))
            })?;

        self.mmio_device_manager
            .complete_all_device_restores()
            .map_err(|e| {
                snapshot::SnapshotError::Deserialize(format!(
                    "Failed to complete device restores: {e}"
                ))
            })?;
        self.mmio_device_manager.resume_all_device_workers();

        self.restore_vcpu_states(vmstate.vcpu_states).map_err(|e| {
            snapshot::SnapshotError::Deserialize(format!("Failed to restore vCPU states: {e}"))
        })?;
        Ok(())
    }

    /// Sends a resume command to the vcpus.
    pub fn resume_vcpus(&mut self) -> Result<()> {
        for handle in self.vcpus_handles.iter() {
            handle
                .send_event(VcpuEvent::Resume)
                .map_err(Error::VcpuEvent)?;
        }
        for handle in self.vcpus_handles.iter() {
            match handle
                .response_receiver()
                .recv_timeout(Duration::from_millis(1000))
            {
                Ok(VcpuResponse::Resumed) => (),
                _ => return Err(Error::VcpuResume),
            }
        }
        Ok(())
    }

    /// Configures the system for boot.
    pub fn configure_system(
        &self,
        vcpus: &[Vcpu],
        _intc: &IrqChip,
        initrd: &Option<InitrdConfig>,
        _smbios_oem_strings: &Option<Vec<String>>,
    ) -> Result<()> {
        #[cfg(target_arch = "x86_64")]
        {
            let cmdline_len = if cfg!(feature = "tee") {
                arch::x86_64::layout::CMDLINE_SEV_SIZE
            } else {
                self.kernel_cmdline.len() + 1
            };

            arch::x86_64::configure_system(
                &self.guest_memory,
                &self.arch_memory_info,
                vm_memory::GuestAddress(arch::x86_64::layout::CMDLINE_START),
                cmdline_len,
                initrd,
                vcpus.len() as u8,
            )
            .map_err(Error::ConfigureSystem)?;
        }

        #[cfg(target_arch = "aarch64")]
        {
            let vcpu_mpidr = vcpus.iter().map(|cpu| cpu.get_mpidr()).collect();
            fdt::create_fdt(
                &self.guest_memory,
                &self.arch_memory_info,
                vcpu_mpidr,
                self.kernel_cmdline.as_str(),
                self.mmio_device_manager.get_device_info(),
                _intc,
                initrd,
            )
            .map_err(Error::SetupFDT)?;
        }

        #[cfg(target_arch = "aarch64")]
        {
            arch::aarch64::configure_system(
                &self.guest_memory,
                &self.arch_memory_info,
                _smbios_oem_strings,
            )
            .map_err(Error::ConfigureSystem)?;
        }

        #[cfg(target_arch = "riscv64")]
        {
            fdt::create_fdt(
                &self.guest_memory,
                &self.arch_memory_info,
                vcpus.len() as u32,
                self.kernel_cmdline.as_str(),
                self.mmio_device_manager.get_device_info(),
                _intc,
                initrd,
            )
            .map_err(Error::SetupFDT)?;

            arch::riscv64::configure_system(&self.guest_memory, _smbios_oem_strings)
                .map_err(Error::ConfigureSystem)?;
        }

        Ok(())
    }

    /// Returns a reference to the guest memory.
    pub fn guest_memory(&self) -> &GuestMemoryMmap {
        &self.guest_memory
    }

    /// Returns a reference to the arch memory info.
    pub fn arch_memory_info(&self) -> &ArchMemoryInfo {
        &self.arch_memory_info
    }

    /// Create a full snapshot of the VM. vCPUs must already be paused.
    #[cfg(all(target_os = "macos", feature = "snapshot"))]
    pub fn create_snapshot(
        &mut self,
        path: &std::path::Path,
    ) -> std::result::Result<(), snapshot::SnapshotError> {
        // Save device state before vCPU state (Firecracker convention: device
        // save may trigger interrupts that should be captured in vCPU state).
        let device_states = self
            .mmio_device_manager
            .save_all_device_states()
            .map_err(|e| {
                snapshot::SnapshotError::Serialize(format!("Failed to save device states: {e}"))
            })?;

        let vcpu_states = self.save_vcpu_states().map_err(|e| {
            snapshot::SnapshotError::Serialize(format!("Failed to save vCPU states: {e}"))
        })?;

        let serialized_vcpu_states: Vec<Vec<u8>> = vcpu_states
            .iter()
            .map(|s| {
                bincode::serialize(s).map_err(|e| snapshot::SnapshotError::Serialize(e.to_string()))
            })
            .collect::<std::result::Result<_, _>>()?;

        let gic_state = self.save_interrupt_controller_state()?;

        snapshot::create_full_snapshot(
            path,
            &self.guest_memory,
            serialized_vcpu_states,
            device_states,
            gic_state,
            None,  // vm_state: not needed on macOS/aarch64
            false, // TODO: get nested_enabled from VM config
        )
    }

    /// Restore a full snapshot into the running VM. vCPUs must already be paused.
    #[cfg(all(target_os = "macos", feature = "snapshot"))]
    pub fn restore_snapshot(
        &mut self,
        path: &std::path::Path,
    ) -> std::result::Result<(), snapshot::SnapshotError> {
        let vmstate = snapshot::load_vmstate(&path.join("vmstate"))?;
        snapshot::validate_header_for_vm(
            &vmstate.header,
            &self.guest_memory,
            self.vcpus_handles.len(),
            self.nested_enabled,
        )?;

        // Quiesce all async device workers before overwriting guest memory.
        // Workers may hold VolatileSliceGuard pointers into guest RAM; if we
        // overwrite memory while they're mid-operation, they'll corrupt the
        // restored state (e.g. writing stale used-ring entries → NETDEV WATCHDOG).
        self.mmio_device_manager
            .quiesce_all_device_workers(snapshot::SNAPSHOT_QUIESCE_TIMEOUT)
            .map_err(|e| {
                snapshot::SnapshotError::Deserialize(format!(
                    "Failed to quiesce device workers before restore: {e}"
                ))
            })?;

        snapshot::load_memory(&self.guest_memory, &path.join("memory"))?;

        // Phase 1: Restore all state without spawning any threads.
        // Device state is deserialized but activate() is deferred.
        if let Some(gic_data) = &vmstate.gic_state {
            self.restore_interrupt_controller_state(gic_data)?;
        }
        self.mmio_device_manager
            .restore_all_device_states(&vmstate.device_states)
            .map_err(|e| {
                snapshot::SnapshotError::Deserialize(format!(
                    "Failed to restore device states: {e}"
                ))
            })?;

        // Phase 2: Now that all state is loaded, activate devices (spawning
        // threads) and kick workers. Threads can safely fire IRQs because
        // interrupt controller state is already in place.
        self.mmio_device_manager
            .complete_all_device_restores()
            .map_err(|e| {
                snapshot::SnapshotError::Deserialize(format!(
                    "Failed to complete device restores: {e}"
                ))
            })?;
        self.mmio_device_manager.resume_all_device_workers();

        let vcpu_states: Vec<hvf::Aarch64VcpuState> = vmstate
            .vcpu_states
            .iter()
            .map(|data| {
                bincode::deserialize(data)
                    .map_err(|e| snapshot::SnapshotError::Deserialize(e.to_string()))
            })
            .collect::<std::result::Result<_, _>>()?;

        self.restore_vcpu_states(vcpu_states).map_err(|e| {
            snapshot::SnapshotError::Deserialize(format!("Failed to restore vCPU states: {e}"))
        })?;
        Ok(())
    }

    /// Enable dirty page tracking. vCPUs must be paused.
    /// After this call, all RAM writes will be tracked via write-protect faults.
    #[cfg(target_os = "macos")]
    pub fn enable_dirty_tracking(&mut self) -> Result<()> {
        use vm_memory::{GuestMemory, GuestMemoryRegion};

        self.dirty_bitmaps.clear();
        let mut ram_regions = Vec::new();
        for region in self.guest_memory.iter() {
            let base = region.start_addr().raw_value();
            let size = region.len();
            self.dirty_bitmaps
                .push(dirty_bitmap::DirtyBitmap::new(base, size));
            ram_regions.push((base, size));

            Vm::protect_memory(base, size, true, false, true).map_err(Error::Vm)?;
        }

        let bitmaps_ptr = &self.dirty_bitmaps as *const Vec<dirty_bitmap::DirtyBitmap>;
        for handle in self.vcpus_handles.iter() {
            let bitmaps_ptr_copy = bitmaps_ptr as usize;
            let ram_regions_clone = ram_regions.clone();

            let callback: hvf::DirtyCallback = Box::new(move |page_addr| {
                let bitmaps =
                    unsafe { &*(bitmaps_ptr_copy as *const Vec<dirty_bitmap::DirtyBitmap>) };
                for bitmap in bitmaps.iter() {
                    if bitmap.contains(page_addr) {
                        bitmap.mark_dirty(page_addr);
                        return;
                    }
                }
            });

            let config = crate::vstate::DirtyTrackingConfig {
                ram_regions: ram_regions_clone,
                dirty_callback: callback,
            };

            handle
                .send_event(VcpuEvent::EnableDirtyTracking(Box::new(config)))
                .map_err(Error::VcpuEvent)?;
        }

        self.dirty_tracking_enabled = true;

        Ok(())
    }

    /// Disable dirty page tracking. vCPUs must be paused.
    #[cfg(target_os = "macos")]
    pub fn disable_dirty_tracking(&mut self) -> Result<()> {
        use vm_memory::{GuestMemory, GuestMemoryRegion};

        for region in self.guest_memory.iter() {
            let base = region.start_addr().raw_value();
            let size = region.len();
            Vm::protect_memory(base, size, true, true, true).map_err(Error::Vm)?;
        }

        for handle in self.vcpus_handles.iter() {
            handle
                .send_event(VcpuEvent::DisableDirtyTracking)
                .map_err(Error::VcpuEvent)?;
        }

        self.dirty_bitmaps.clear();
        Ok(())
    }

    /// Create an incremental snapshot (dirty pages only). vCPUs must be paused.
    #[cfg(all(target_os = "macos", feature = "snapshot"))]
    pub fn create_incremental_snapshot(
        &mut self,
        path: &std::path::Path,
    ) -> std::result::Result<(), snapshot::SnapshotError> {
        use vm_memory::{GuestAddress, GuestMemory, GuestMemoryRegion};

        if !self.dirty_tracking_enabled {
            return Err(snapshot::SnapshotError::DirtyTrackingNotEnabled);
        }

        // Save device state before vCPU state (Firecracker convention).
        let device_states = self
            .mmio_device_manager
            .save_all_device_states()
            .map_err(|e| {
                snapshot::SnapshotError::Serialize(format!("Failed to save device states: {e}"))
            })?;

        let vcpu_states = self.save_vcpu_states().map_err(|e| {
            snapshot::SnapshotError::Serialize(format!("Failed to save vCPU states: {e}"))
        })?;

        let serialized_vcpu_states: Vec<Vec<u8>> = vcpu_states
            .iter()
            .map(|s| {
                bincode::serialize(s).map_err(|e| snapshot::SnapshotError::Serialize(e.to_string()))
            })
            .collect::<std::result::Result<_, _>>()?;

        let gic_state = self.save_interrupt_controller_state()?;

        let mut dirty_pages = Vec::new();
        for bitmap in &self.dirty_bitmaps {
            let dirty_addrs = bitmap.drain_dirty_pages();
            for addr in dirty_addrs {
                let host_ptr = self
                    .guest_memory
                    .get_host_address(GuestAddress(addr))
                    .map_err(|e| {
                        snapshot::SnapshotError::Serialize(format!(
                            "Invalid guest address for dirty page 0x{addr:x}: {e}"
                        ))
                    })?;
                let page_data = unsafe {
                    std::slice::from_raw_parts(host_ptr, dirty_bitmap::PAGE_SIZE as usize)
                };
                dirty_pages.push(snapshot::DirtyPage {
                    guest_addr: addr,
                    data: page_data.to_vec(),
                });
            }
        }

        for region in self.guest_memory.iter() {
            let base = region.start_addr().raw_value();
            let size = region.len();
            Vm::protect_memory(base, size, true, false, true).map_err(|e| {
                snapshot::SnapshotError::Io(std::io::Error::new(
                    std::io::ErrorKind::Other,
                    format!("{e}"),
                ))
            })?;
        }

        let incremental = snapshot::IncrementalSnapshot {
            header: snapshot::SnapshotHeader {
                magic: snapshot::SNAPSHOT_MAGIC,
                version: snapshot::SNAPSHOT_VERSION,
                vcpu_count: serialized_vcpu_states.len() as u32,
                ram_regions: snapshot::ram_layout(&self.guest_memory),
                nested_enabled: self.nested_enabled,
            },
            vcpu_states: serialized_vcpu_states,
            device_states,
            dirty_pages,
            gic_state,
            vm_state: None,
        };

        snapshot::save_incremental_snapshot(&incremental, path)
    }

    /// Restore an incremental snapshot. vCPUs must already be paused.
    #[cfg(all(target_os = "macos", feature = "snapshot"))]
    pub fn restore_incremental_snapshot(
        &mut self,
        path: &std::path::Path,
    ) -> std::result::Result<(), snapshot::SnapshotError> {
        let incremental = snapshot::load_incremental_snapshot(path)?;
        snapshot::validate_header_for_vm(
            &incremental.header,
            &self.guest_memory,
            self.vcpus_handles.len(),
            self.nested_enabled,
        )?;

        // Quiesce all async device workers before overwriting guest memory.
        // Same race as restore_snapshot: workers may hold raw pointers into
        // guest RAM during in-flight I/O.
        self.mmio_device_manager
            .quiesce_all_device_workers(snapshot::SNAPSHOT_QUIESCE_TIMEOUT)
            .map_err(|e| {
                snapshot::SnapshotError::Deserialize(format!(
                    "Failed to quiesce device workers before restore: {e}"
                ))
            })?;

        snapshot::apply_dirty_pages(&self.guest_memory, &incremental.dirty_pages)?;

        // Phase 1: Restore all state without spawning any threads.
        if let Some(gic_data) = &incremental.gic_state {
            self.restore_interrupt_controller_state(gic_data)?;
        }
        self.mmio_device_manager
            .restore_all_device_states(&incremental.device_states)
            .map_err(|e| {
                snapshot::SnapshotError::Deserialize(format!(
                    "Failed to restore device states: {e}"
                ))
            })?;

        // Phase 2: Activate devices (if needed) and kick workers.
        self.mmio_device_manager
            .complete_all_device_restores()
            .map_err(|e| {
                snapshot::SnapshotError::Deserialize(format!(
                    "Failed to complete device restores: {e}"
                ))
            })?;
        self.mmio_device_manager.resume_all_device_workers();

        let vcpu_states: Vec<hvf::Aarch64VcpuState> = incremental
            .vcpu_states
            .iter()
            .map(|data| {
                bincode::deserialize(data)
                    .map_err(|e| snapshot::SnapshotError::Deserialize(e.to_string()))
            })
            .collect::<std::result::Result<_, _>>()?;

        self.restore_vcpu_states(vcpu_states).map_err(|e| {
            snapshot::SnapshotError::Deserialize(format!("Failed to restore vCPU states: {e}"))
        })?;
        Ok(())
    }

    /// Enable dirty page tracking via KVM dirty log. vCPUs must be paused.
    #[cfg(all(target_os = "linux", feature = "snapshot"))]
    pub fn enable_dirty_tracking(&mut self) -> Result<()> {
        use kvm_bindings::{kvm_userspace_memory_region, KVM_MEM_LOG_DIRTY_PAGES};

        for &(slot, guest_addr, size, host_addr) in &self.vm.mem_slots {
            let region = kvm_userspace_memory_region {
                slot,
                guest_phys_addr: guest_addr,
                memory_size: size,
                userspace_addr: host_addr,
                flags: KVM_MEM_LOG_DIRTY_PAGES,
            };
            unsafe {
                self.vm
                    .fd()
                    .set_user_memory_region(region)
                    .map_err(|e| Error::Vm(vstate::Error::SetUserMemoryRegion(e)))?;
            }
        }
        self.dirty_tracking_enabled = true;
        Ok(())
    }

    /// Collect dirty pages from KVM dirty log.
    #[cfg(all(target_os = "linux", feature = "snapshot"))]
    fn collect_dirty_pages(
        &self,
    ) -> std::result::Result<Vec<snapshot::DirtyPage>, snapshot::SnapshotError> {
        use vm_memory::{GuestAddress, GuestMemory};

        let page_size = 4096u64;
        let mut pages = Vec::new();
        for &(slot, guest_addr, size, _) in &self.vm.mem_slots {
            let bitmap = self
                .vm
                .fd()
                .get_dirty_log(slot, size as usize)
                .map_err(|e| {
                    snapshot::SnapshotError::Serialize(format!(
                        "Failed to get dirty log for slot {slot}: {e}"
                    ))
                })?;
            for (word_idx, &word) in bitmap.iter().enumerate() {
                if word == 0 {
                    continue;
                }
                for bit in 0..64u32 {
                    if (word >> bit) & 1 != 0 {
                        let page_idx = word_idx as u64 * 64 + bit as u64;
                        let addr = guest_addr + page_idx * page_size;
                        let host_ptr = self
                            .guest_memory
                            .get_host_address(GuestAddress(addr))
                            .map_err(|e| {
                                snapshot::SnapshotError::Serialize(format!(
                                    "Invalid guest address for dirty page 0x{addr:x}: {e}"
                                ))
                            })?;
                        let data =
                            unsafe { std::slice::from_raw_parts(host_ptr, page_size as usize) };
                        pages.push(snapshot::DirtyPage {
                            guest_addr: addr,
                            data: data.to_vec(),
                        });
                    }
                }
            }
        }
        Ok(pages)
    }

    /// Create an incremental snapshot (dirty pages only). vCPUs must be paused.
    #[cfg(all(target_os = "linux", feature = "snapshot"))]
    pub fn create_incremental_snapshot(
        &mut self,
        path: &std::path::Path,
    ) -> std::result::Result<(), snapshot::SnapshotError> {
        if !self.dirty_tracking_enabled {
            return Err(snapshot::SnapshotError::DirtyTrackingNotEnabled);
        }

        let device_states = self
            .mmio_device_manager
            .save_all_device_states()
            .map_err(|e| {
                snapshot::SnapshotError::Serialize(format!("Failed to save device states: {e}"))
            })?;

        let vcpu_states = self.save_vcpu_states().map_err(|e| {
            snapshot::SnapshotError::Serialize(format!("Failed to save vCPU states: {e}"))
        })?;

        #[cfg(target_arch = "aarch64")]
        let gic_state = self.save_interrupt_controller_state()?;
        #[cfg(not(target_arch = "aarch64"))]
        let gic_state = None;

        #[cfg(target_arch = "x86_64")]
        let vm_state = Some(
            bincode::serialize(&self.vm.save_state().map_err(|e| {
                snapshot::SnapshotError::Serialize(format!("Failed to save VM state: {e}"))
            })?)
            .map_err(|e| snapshot::SnapshotError::Serialize(e.to_string()))?,
        );
        #[cfg(not(target_arch = "x86_64"))]
        let vm_state = None;

        let dirty_pages = self.collect_dirty_pages()?;

        let incremental = snapshot::IncrementalSnapshot {
            header: snapshot::SnapshotHeader {
                magic: snapshot::SNAPSHOT_MAGIC,
                version: snapshot::SNAPSHOT_VERSION,
                vcpu_count: vcpu_states.len() as u32,
                ram_regions: snapshot::ram_layout(&self.guest_memory),
                nested_enabled: self.nested_enabled,
            },
            vcpu_states,
            device_states,
            dirty_pages,
            gic_state,
            vm_state,
        };

        snapshot::save_incremental_snapshot(&incremental, path)
    }

    /// Restore an incremental snapshot. vCPUs must already be paused.
    #[cfg(all(target_os = "linux", feature = "snapshot"))]
    pub fn restore_incremental_snapshot(
        &mut self,
        path: &std::path::Path,
    ) -> std::result::Result<(), snapshot::SnapshotError> {
        let incremental = snapshot::load_incremental_snapshot(path)?;
        snapshot::validate_header_for_vm(
            &incremental.header,
            &self.guest_memory,
            self.vcpus_handles.len(),
            self.nested_enabled,
        )?;

        self.mmio_device_manager
            .quiesce_all_device_workers(snapshot::SNAPSHOT_QUIESCE_TIMEOUT)
            .map_err(|e| {
                snapshot::SnapshotError::Deserialize(format!(
                    "Failed to quiesce device workers before restore: {e}"
                ))
            })?;

        snapshot::apply_dirty_pages(&self.guest_memory, &incremental.dirty_pages)?;

        #[cfg(target_arch = "aarch64")]
        if let Some(gic_data) = &incremental.gic_state {
            self.restore_interrupt_controller_state(gic_data)?;
        }

        #[cfg(target_arch = "x86_64")]
        if let Some(data) = &incremental.vm_state {
            let state: vstate::VmState = bincode::deserialize(data)
                .map_err(|e| snapshot::SnapshotError::Deserialize(e.to_string()))?;
            self.vm.restore_state(&state).map_err(|e| {
                snapshot::SnapshotError::Deserialize(format!("Failed to restore VM state: {e}"))
            })?;
        }

        self.mmio_device_manager
            .restore_all_device_states(&incremental.device_states)
            .map_err(|e| {
                snapshot::SnapshotError::Deserialize(format!(
                    "Failed to restore device states: {e}"
                ))
            })?;

        self.mmio_device_manager
            .complete_all_device_restores()
            .map_err(|e| {
                snapshot::SnapshotError::Deserialize(format!(
                    "Failed to complete device restores: {e}"
                ))
            })?;
        self.mmio_device_manager.resume_all_device_workers();

        self.restore_vcpu_states(incremental.vcpu_states)
            .map_err(|e| {
                snapshot::SnapshotError::Deserialize(format!("Failed to restore vCPU states: {e}"))
            })?;
        Ok(())
    }

    /// Injects CTRL+ALT+DEL keystroke combo in the i8042 device.
    #[cfg(target_arch = "x86_64")]
    pub fn send_ctrl_alt_del(&mut self) -> Result<()> {
        self.pio_device_manager
            .i8042
            .lock()
            .expect("i8042 lock was poisoned")
            .trigger_ctrl_alt_del()
            .map_err(Error::I8042Error)
    }

    /// Waits for all vCPUs to exit and stores exit information in shared state.
    pub fn stop(&mut self, vm_exit: crate::vm_exit::VmExit) {
        info!("Vmm is stopping: {vm_exit:?}");

        // Run exit observers first (AC3.1)
        for observer in &self.exit_observers {
            observer
                .lock()
                .expect("Poisoned mutex for exit observer")
                .on_vmm_exit();
        }

        // Signal vCPU threads to exit their blocking state (AC3.2)
        self.vcpu_exit_flag.store(true, Ordering::Release);

        // Store the exit reason for Context::run() to read
        *self.vm_exit.lock().expect("Poisoned vm_exit lock") = Some(vm_exit);
    }

    /// Returns a reference to the inner KVM Vm object.
    pub fn kvm_vm(&self) -> &Vm {
        &self.vm
    }

    #[cfg(target_os = "macos")]
    pub fn add_mapping(
        &self,
        reply_sender: Sender<bool>,
        host_addr: u64,
        guest_addr: u64,
        len: u64,
    ) {
        self.vm
            .add_mapping(reply_sender, host_addr, guest_addr, len);
    }

    #[cfg(target_os = "macos")]
    pub fn remove_mapping(&self, reply_sender: Sender<bool>, guest_addr: u64, len: u64) {
        self.vm.remove_mapping(reply_sender, guest_addr, len);
    }
}

impl Subscriber for Vmm {
    /// Handle a read event (EPOLLIN).
    fn process(&mut self, event: &EpollEvent, _: &mut EventManager) {
        let source = event.fd();
        let event_set = event.event_set();

        if source == self.exit_evt.as_raw_fd() && event_set == EventSet::IN {
            debug!("Vmm: exit_evt fired, shutting down");
            let _ = self.exit_evt.read();

            let vcpu_exit_code = self
                .vcpus_handles
                .iter()
                .find_map(|handle| match handle.response_receiver().try_recv() {
                    Ok(VcpuResponse::Exited(exit_code)) => Some(exit_code),
                    _ => None,
                })
                .unwrap_or(FC_EXIT_CODE_OK);

            let vmm_exit_code = self.exit_code.load(Ordering::SeqCst);

            // Log which exit code is being used for shutdown
            if vmm_exit_code != i32::MAX {
                debug!("using vmm exit code: {vmm_exit_code}");
            } else {
                debug!("using vcpu exit code: {vcpu_exit_code}");
            }

            let vm_exit = resolve_vm_exit(vcpu_exit_code, vmm_exit_code);
            self.stop(vm_exit);
        } else {
            error!("Spurious EventManager event for handler: Vmm");
        }
    }

    fn interest_list(&self) -> Vec<EpollEvent> {
        vec![EpollEvent::new(
            EventSet::IN,
            self.exit_evt.as_raw_fd() as u64,
        )]
    }
}

/// Helper function to resolve VmExit variant from exit codes.
/// This is the core logic used by Subscriber::process() to determine
/// the correct VmExit variant based on vCPU exit code and VMM exit code.
/// Tests call this same function to verify the dispatch logic.
pub(crate) fn resolve_vm_exit(vcpu_exit_code: u8, vmm_exit_code: i32) -> crate::vm_exit::VmExit {
    if vcpu_exit_code == FC_EXIT_CODE_REBOOT {
        crate::vm_exit::VmExit::RebootRequested
    } else if vcpu_exit_code == FC_EXIT_CODE_GENERIC_ERROR {
        crate::vm_exit::VmExit::Error {
            message: "vCPU fatal error".into(),
        }
    } else {
        let exit_code = if vmm_exit_code != i32::MAX {
            vmm_exit_code
        } else {
            vcpu_exit_code as i32
        };
        crate::vm_exit::VmExit::Shutdown { exit_code }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Helper function to check if dirty tracking is enabled.
    /// This is used in both create_incremental_snapshot implementations.
    fn check_dirty_tracking_enabled(
        dirty_tracking_enabled: bool,
    ) -> std::result::Result<(), snapshot::SnapshotError> {
        if !dirty_tracking_enabled {
            return Err(snapshot::SnapshotError::DirtyTrackingNotEnabled);
        }
        Ok(())
    }

    /// AC1.9: create_incremental_snapshot requires dirty_tracking_enabled
    #[test]
    fn test_incremental_snapshot_requires_dirty_tracking() {
        // Guard check before dirty_tracking was enabled
        let result = check_dirty_tracking_enabled(false);
        assert!(matches!(
            result,
            Err(snapshot::SnapshotError::DirtyTrackingNotEnabled)
        ));

        // Guard check after dirty_tracking is enabled
        let result = check_dirty_tracking_enabled(true);
        assert!(result.is_ok());
    }

    /// Test VM exit enum variants and derives
    #[test]
    fn test_vm_exit_enum() {
        // Test Shutdown variant construction and clone
        let exit_shutdown = crate::vm_exit::VmExit::Shutdown { exit_code: 0 };
        let exit_shutdown_cloned = exit_shutdown.clone();
        assert_eq!(exit_shutdown, exit_shutdown_cloned);

        // Test different exit codes
        let exit_42 = crate::vm_exit::VmExit::Shutdown { exit_code: 42 };
        assert_ne!(exit_shutdown, exit_42);

        // Test RebootRequested variant
        let exit_reboot = crate::vm_exit::VmExit::RebootRequested;
        let exit_reboot_cloned = exit_reboot.clone();
        assert_eq!(exit_reboot, exit_reboot_cloned);

        // Test Error variant
        let exit_error = crate::vm_exit::VmExit::Error {
            message: "test error".into(),
        };
        let exit_error_cloned = exit_error.clone();
        assert_eq!(exit_error, exit_error_cloned);

        // Test Debug trait
        let debug_str = format!("{:?}", exit_shutdown);
        assert!(debug_str.contains("Shutdown"));
    }

    /// Test vm-exit.AC1.1: Normal guest shutdown (HLT) returns Shutdown { exit_code: 0 }
    #[test]
    fn test_shutdown_with_zero_exit_code() {
        let vm_exit = resolve_vm_exit(FC_EXIT_CODE_OK, i32::MAX);
        assert_eq!(
            vm_exit,
            crate::vm_exit::VmExit::Shutdown { exit_code: 0 }
        );
    }

    /// Test vm-exit.AC1.2: Guest-set exit code is returned in Shutdown variant
    #[test]
    fn test_shutdown_with_guest_exit_code() {
        // Guest set exit code via vmm_exit_code (virtio-fs ioctl)
        let vm_exit = resolve_vm_exit(FC_EXIT_CODE_OK, 42);
        assert_eq!(
            vm_exit,
            crate::vm_exit::VmExit::Shutdown { exit_code: 42 }
        );
    }

    /// Test vm-exit.AC1.3: KVM_SYSTEM_EVENT_RESET returns RebootRequested
    #[test]
    fn test_reboot_requested() {
        let vm_exit = resolve_vm_exit(FC_EXIT_CODE_REBOOT, i32::MAX);
        assert_eq!(vm_exit, crate::vm_exit::VmExit::RebootRequested);
    }

    /// Test vm-exit.AC2.1: vCPU fatal errors return Error variant
    #[test]
    fn test_vcpu_fatal_error() {
        let vm_exit = resolve_vm_exit(FC_EXIT_CODE_GENERIC_ERROR, i32::MAX);
        match vm_exit {
            crate::vm_exit::VmExit::Error { ref message } => {
                assert_eq!(message, "vCPU fatal error");
            }
            _ => panic!("Expected Error variant"),
        }
    }

    /// Test shared exit state storage contract
    #[test]
    fn test_shared_vm_exit_storage() {
        let vm_exit: crate::vm_exit::SharedVmExit =
            Arc::new(Mutex::new(None));

        // Initially should be None
        {
            let guard = vm_exit.lock().expect("Poisoned lock");
            assert!(guard.is_none());
        }

        // Store a VmExit value
        {
            let mut guard = vm_exit.lock().expect("Poisoned lock");
            *guard = Some(crate::vm_exit::VmExit::Shutdown { exit_code: 0 });
        }

        // Verify it was stored
        {
            let guard = vm_exit.lock().expect("Poisoned lock");
            assert_eq!(
                *guard,
                Some(crate::vm_exit::VmExit::Shutdown { exit_code: 0 })
            );
        }
    }
}
