[package]
name = "test_cases"
edition = "2021"

[features]
host = ["krun-sys", "dep:libkrun"]
guest = []

[lib]
name = "test_cases"

[dependencies]
krun-sys = { path = "../../krun-sys", optional = true }
libkrun = { path = "../../src/libkrun", optional = true, features = ["embedded_init", "net", "blk", "snapshot"] }
macros = { path = "../macros" }
nix = { version = "0.29.0", features = ["socket"] }
libc = "0.2"
anyhow = "1.0.95"
tempdir = "0.3.7"
tokio = { version = "1", features = ["sync"] }
bytes = "1"
pnet = "0.35"
