[workspace]
members = ["src/libkrun", "src/krun_input"]
exclude = ["examples/gtk_display", "fuzz"]
resolver = "2"

[profile.dev]
#panic = "abort"

[profile.release]
#panic = "abort"
lto = true

[profile.profiling]
inherits = "release"
debug = true
lto = false

[patch.crates-io]
linux-loader = { git = "https://github.com/theoparis/linux-loader", rev = "af90928dcfa1666d47a5269061ef77857eff46d3" }
vhost = { path = "vendor/vhost" }
tdx = { path = "vendor/tdx" }
