[workspace]
members = ["src/libkrun", "src/krun_input"]
exclude = ["examples/gtk_display"]
resolver = "2"

[profile.dev]
#panic = "abort"

[profile.release]
#panic = "abort"
lto = true

[profile.profiling]
inherits = "release"
debug = true
lto = false

[patch.crates-io]
vhost = { path = "vendor/vhost" }
